import { OrderRecord } from "@/services/order.service";

export const INITIAL_MOCK_ORDERS: OrderRecord[] = [
  // 1. Shipped Air Export Order (B2B Wholesale - London, UK)
  {
    id: "ord_1001",
    order_number: "AYN-20260824-001045",
    user_id: 102,
    status: "shipped",
    payment_status: "paid",
    fulfillment_status: "shipped",
    currency: "USD",
    email: "buyer@ayaanclothing.com",
    shipping_name: "Marcus Vance",
    shipping_company: "Vance & Co Retail Ltd",
    shipping_phone: "+44 20 7946 0912",
    shipping_address1: "12 Oxford Street",
    shipping_address2: "Suite 400",
    shipping_city: "London",
    shipping_region: "Greater London",
    shipping_postal_code: "W1D 1BS",
    shipping_country_code: "GB",
    shipping_method: "Aramex Priority Air Express",
    carrier: "Aramex Express Air",
    tracking_number: "AWB-8801928374",
    shipment_id: "SHP-ARX-99481",
    direct_tracking_url: "https://www.aramex.com/track/results?shipmentNumber=8801928374",
    carrier_status: "In Transit to London Heathrow (LHR)",
    last_carrier_update: "Cleared export customs at Dhaka Airport (DAC)",
    shipping_snapshot: {
      provider: "aramex",
      mode: "air",
      shipping_method: "Aramex Priority Air Express",
      carrier: "Aramex Express Air",
      tracking_number: "AWB-8801928374",
      package_quantity: 500,
      carton_count: 10,
      gross_weight: 120,
      net_weight: 110,
      cbm: 0.45,
      destination_port: "London Heathrow (LHR)",
      service_type: "Priority Air Express",
    },
    payment_method: "bank_transfer",
    subtotal: 4000.00,
    subtotal_cents: 400000,
    shipping_cost: 320.00,
    shipping_cents: 32000,
    tax_amount: 0,
    tax_cents: 0,
    discount_amount: 0,
    discount_cents: 0,
    total_amount: 4320.00,
    total_cents: 432000,
    placed_at: "2026-08-24T14:30:00Z",
    created_at: "2026-08-24T14:30:00Z",
    updated_at: "2026-08-27T09:15:00Z",
    items: [
      {
        id: "item_1001_1",
        order_id: "ord_1001",
        product_id: "prd0001",
        product_name: "Essential Cotton Crew T-Shirt",
        product_slug: "essential-cotton-crew-t-shirt",
        product_image_url: "https://images.pexels.com/photos/7658459/pexels-photo-7658459.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        sku: "AYN-TSH-001-BLK-M",
        variant_title: "Black / Assorted (M-2XL)",
        size: "Assorted M-2XL",
        color: "Black",
        quantity: 500,
        unit_price: 8.00,
        unit_price_cents: 800,
        line_total: 4000.00,
        line_total_cents: 400000,
        package_breakdown: [
          { size: "M", quantity: 150 },
          { size: "L", quantity: 200 },
          { size: "XL", quantity: 100 },
          { size: "2XL", quantity: 50 },
        ],
      },
    ],
    status_events: [
      {
        id: "ev_1",
        order_id: "ord_1001",
        event_type: "order_placed",
        message: "Commercial export order placed via Net 30 terms.",
        created_at: "2026-08-24T14:30:00Z",
      },
      {
        id: "ev_2",
        order_id: "ord_1001",
        event_type: "payment_succeeded",
        message: "Proforma invoice PI-AYN-20260824-001045 confirmed by accounts.",
        created_at: "2026-08-25T10:00:00Z",
      },
      {
        id: "ev_3",
        order_id: "ord_1001",
        event_type: "fulfillment_processing",
        message: "Finished goods packed in 10 export cartons with standard AQL 2.5 inspection.",
        created_at: "2026-08-26T16:00:00Z",
      },
      {
        id: "ev_4",
        order_id: "ord_1001",
        event_type: "fulfillment_shipped",
        message: "Dispatched with Aramex Priority Air (AWB-8801928374).",
        created_at: "2026-08-27T09:15:00Z",
      },
    ],
    user: {
      id: 102,
      name: "Marcus Vance",
      email: "buyer@ayaanclothing.com",
      company_name: "Vance & Co Retail Ltd",
    },
  },

  // 2. Processing Order with Pending Payment Proof Review
  {
    id: "ord_1002",
    order_number: "AYN-20260901-001092",
    user_id: 101,
    status: "processing",
    payment_status: "pending",
    fulfillment_status: "processing",
    currency: "USD",
    email: "sarah.jenkins@jenkinsapparel.com",
    shipping_name: "Sarah Jenkins",
    shipping_company: "Jenkins Apparel Boutique",
    shipping_phone: "+1-555-0199",
    shipping_address1: "742 Evergreen Terrace",
    shipping_city: "Springfield",
    shipping_region: "OR",
    shipping_postal_code: "97477",
    shipping_country_code: "US",
    shipping_method: "Aramex Priority Air Express",
    carrier: "Aramex Express Air",
    payment_method: "bank_transfer",
    payment_proof_url: "https://images.pexels.com/photos/6863183/pexels-photo-6863183.jpeg?auto=compress&cs=tinysrgb&w=800",
    subtotal: 1600.00,
    subtotal_cents: 160000,
    shipping_cost: 180.00,
    shipping_cents: 18000,
    tax_amount: 0,
    tax_cents: 0,
    discount_amount: 100.00,
    discount_cents: 10000,
    total_amount: 1680.00,
    total_cents: 168000,
    placed_at: "2026-09-01T11:00:00Z",
    created_at: "2026-09-01T11:00:00Z",
    updated_at: "2026-09-01T11:30:00Z",
    items: [
      {
        id: "item_1002_1",
        order_id: "ord_1002",
        product_id: "prd0002",
        product_name: "Classic Denim Trucker Jacket",
        product_slug: "classic-denim-trucker-jacket",
        product_image_url: "https://images.pexels.com/photos/19490409/pexels-photo-19490409.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        sku: "AYN-JNS-002-BLU-S",
        variant_title: "Indigo / S",
        size: "S",
        color: "Indigo",
        quantity: 50,
        unit_price: 32.00,
        unit_price_cents: 3200,
        line_total: 1600.00,
        line_total_cents: 160000,
      },
    ],
    status_events: [
      {
        id: "ev_1002_1",
        order_id: "ord_1002",
        event_type: "order_placed",
        message: "Order placed online with wire receipt uploaded.",
        created_at: "2026-09-01T11:00:00Z",
      },
      {
        id: "ev_1002_2",
        order_id: "ord_1002",
        event_type: "payment_proof_uploaded",
        message: "Customer uploaded bank deposit receipt (Ref #BNK-88291).",
        created_at: "2026-09-01T11:15:00Z",
      },
    ],
    user: {
      id: 101,
      name: "Sarah Jenkins",
      email: "sarah.jenkins@jenkinsapparel.com",
      company_name: "Jenkins Apparel Boutique",
    },
  },

  // 3. Ocean Freight Order (Sea Container FCL - Port of Hamburg, Germany)
  {
    id: "ord_1003",
    order_number: "AYN-20260905-001103",
    user_id: 103,
    status: "confirmed",
    payment_status: "paid",
    fulfillment_status: "unfulfilled",
    currency: "USD",
    email: "j.weber@hanseatic-apparel.de",
    shipping_name: "Johannes Weber",
    shipping_company: "Hanseatic Trading GmbH",
    shipping_phone: "+49 40 1234 5678",
    shipping_address1: "Speicherstadt 24",
    shipping_address2: "Gebäude 3B",
    shipping_city: "Hamburg",
    shipping_region: "Hamburg",
    shipping_postal_code: "20457",
    shipping_country_code: "DE",
    shipping_method: "Ocean Freight Container LCL",
    carrier: "Maersk Line Ocean",
    transport_method: "sea",
    destination_port: "Port of Hamburg (HAM)",
    shipping_quote_id: "QT-SEA-2026-0042",
    shipping_snapshot: {
      provider: "ocean_carrier",
      mode: "sea",
      shipping_method: "Ocean Freight Container LCL",
      carrier: "Maersk Line Ocean",
      package_quantity: 1200,
      carton_count: 24,
      gross_weight: 480,
      net_weight: 440,
      cbm: 1.85,
      destination_port: "Port of Hamburg (HAM)",
      service_type: "Ocean LCL Consolidated",
      quoted_shipping_charge: 650.00,
      notes: "Direct booking from Chittagong Port (CGP) to Hamburg (HAM).",
    },
    payment_method: "letter_of_credit",
    subtotal: 9600.00,
    subtotal_cents: 960000,
    shipping_cost: 650.00,
    shipping_cents: 65000,
    tax_amount: 0,
    tax_cents: 0,
    discount_amount: 250.00,
    discount_cents: 25000,
    total_amount: 10000.00,
    total_cents: 1000000,
    placed_at: "2026-09-05T08:20:00Z",
    created_at: "2026-09-05T08:20:00Z",
    updated_at: "2026-09-06T14:10:00Z",
    items: [
      {
        id: "item_1003_1",
        order_id: "ord_1003",
        product_id: "prd0003",
        product_name: "Linen Long Sleeve Formal Shirt",
        product_slug: "linen-long-sleeve-formal-shirt",
        product_image_url: "https://images.pexels.com/photos/298863/pexels-photo-298863.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        sku: "AYN-SHR-003-WHT-L",
        variant_title: "White / L",
        size: "L",
        color: "White",
        quantity: 600,
        unit_price: 8.00,
        unit_price_cents: 800,
        line_total: 4800.00,
        line_total_cents: 480000,
      },
      {
        id: "item_1003_2",
        order_id: "ord_1003",
        product_id: "prd0004",
        product_name: "Chino Relaxed Fit Trousers",
        product_slug: "chino-relaxed-fit-trousers",
        product_image_url: "https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        sku: "AYN-TRU-004-KHK-32",
        variant_title: "Khaki / 32",
        size: "32",
        color: "Khaki",
        quantity: 600,
        unit_price: 8.00,
        unit_price_cents: 800,
        line_total: 4800.00,
        line_total_cents: 480000,
      },
    ],
    status_events: [
      {
        id: "ev_1003_1",
        order_id: "ord_1003",
        event_type: "order_placed",
        message: "High-volume container export order placed via Irrevocable L/C.",
        created_at: "2026-09-05T08:20:00Z",
      },
      {
        id: "ev_1003_2",
        order_id: "ord_1003",
        event_type: "payment_succeeded",
        message: "LC #LC-DE-99482 verified by Pubali Bank Limited.",
        created_at: "2026-09-06T14:10:00Z",
      },
    ],
    user: {
      id: 103,
      name: "Johannes Weber",
      email: "j.weber@hanseatic-apparel.de",
      company_name: "Hanseatic Trading GmbH",
    },
  },

  // 4. Delivered Order (Retail Customer - Tokyo, Japan)
  {
    id: "ord_1004",
    order_number: "AYN-20260908-001119",
    user_id: 104,
    status: "delivered",
    payment_status: "paid",
    fulfillment_status: "delivered",
    currency: "USD",
    email: "tanaka@ginza-fashion.jp",
    shipping_name: "Hiroshi Tanaka",
    shipping_company: "Ginza Apparel Studio",
    shipping_phone: "+81 3 5555 0142",
    shipping_address1: "4-12-15 Ginza",
    shipping_address2: "Ginza Tower 6F",
    shipping_city: "Chuo-ku",
    shipping_region: "Tokyo",
    shipping_postal_code: "104-0061",
    shipping_country_code: "JP",
    shipping_method: "DHL International Express",
    carrier: "DHL Express",
    tracking_number: "AWB-9182736450",
    carrier_status: "Delivered & Signed by Reception",
    last_carrier_update: "Package delivered to consignee",
    payment_method: "card",
    subtotal: 2400.00,
    subtotal_cents: 240000,
    shipping_cost: 210.00,
    shipping_cents: 21000,
    tax_amount: 0,
    tax_cents: 0,
    discount_amount: 0,
    discount_cents: 0,
    total_amount: 2610.00,
    total_cents: 261000,
    placed_at: "2026-09-08T03:15:00Z",
    created_at: "2026-09-08T03:15:00Z",
    updated_at: "2026-09-12T16:45:00Z",
    items: [
      {
        id: "item_1004_1",
        order_id: "ord_1004",
        product_id: "prd0005",
        product_name: "Oversized Heavyweight Hoodie",
        product_slug: "oversized-heavyweight-hoodie",
        product_image_url: "https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        sku: "AYN-HD-005-GRY-XL",
        variant_title: "Heather Grey / XL",
        size: "XL",
        color: "Heather Grey",
        quantity: 120,
        unit_price: 20.00,
        unit_price_cents: 2000,
        line_total: 2400.00,
        line_total_cents: 240000,
      },
    ],
    status_events: [
      {
        id: "ev_1004_1",
        order_id: "ord_1004",
        event_type: "order_placed",
        message: "Order placed via online checkout.",
        created_at: "2026-09-08T03:15:00Z",
      },
      {
        id: "ev_1004_2",
        order_id: "ord_1004",
        event_type: "fulfillment_delivered",
        message: "Shipment delivered and signed at Tokyo destination.",
        created_at: "2026-09-12T16:45:00Z",
      },
    ],
    user: {
      id: 104,
      name: "Hiroshi Tanaka",
      email: "tanaka@ginza-fashion.jp",
      company_name: "Ginza Apparel Studio",
    },
  },

  // 5. Pending Verification Order (New Buyer - Dubai, UAE)
  {
    id: "ord_1005",
    order_number: "AYN-20260910-001134",
    user_id: 105,
    status: "pending",
    payment_status: "pending",
    fulfillment_status: "unfulfilled",
    currency: "USD",
    email: "ahmed.mansoor@gulftextiles.ae",
    shipping_name: "Ahmed Al-Mansoor",
    shipping_company: "Gulf Textiles & Trade LLC",
    shipping_phone: "+971 4 398 7654",
    shipping_address1: "Al Quoz Industrial Area 3",
    shipping_address2: "Warehouse 14B",
    shipping_city: "Dubai",
    shipping_region: "Dubai",
    shipping_postal_code: "338-120",
    shipping_country_code: "AE",
    shipping_method: "Aramex Priority Air Express",
    carrier: "Aramex Express Air",
    payment_method: "bank_transfer",
    subtotal: 3500.00,
    subtotal_cents: 350000,
    shipping_cost: 290.00,
    shipping_cents: 29000,
    tax_amount: 0,
    tax_cents: 0,
    discount_amount: 0,
    discount_cents: 0,
    total_amount: 3790.00,
    total_cents: 379000,
    placed_at: "2026-09-10T10:00:00Z",
    created_at: "2026-09-10T10:00:00Z",
    updated_at: "2026-09-10T10:00:00Z",
    items: [
      {
        id: "item_1005_1",
        order_id: "ord_1005",
        product_id: "prd0006",
        product_name: "Premium Pima Cotton Polo",
        product_slug: "premium-pima-cotton-polo",
        product_image_url: "https://images.pexels.com/photos/1232459/pexels-photo-1232459.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        sku: "AYN-POLO-006-NAV-M",
        variant_title: "Navy / M",
        size: "M",
        color: "Navy",
        quantity: 250,
        unit_price: 14.00,
        unit_price_cents: 1400,
        line_total: 3500.00,
        line_total_cents: 350000,
      },
    ],
    status_events: [
      {
        id: "ev_1005_1",
        order_id: "ord_1005",
        event_type: "order_placed",
        message: "Proforma Invoice generated. Awaiting bank remittance.",
        created_at: "2026-09-10T10:00:00Z",
      },
    ],
    user: {
      id: 105,
      name: "Ahmed Al-Mansoor",
      email: "ahmed.mansoor@gulftextiles.ae",
      company_name: "Gulf Textiles & Trade LLC",
    },
  },

  // 6. Cancelled Order
  {
    id: "ord_1006",
    order_number: "AYN-20260912-001150",
    user_id: 106,
    status: "cancelled",
    payment_status: "failed",
    fulfillment_status: "unfulfilled",
    currency: "USD",
    email: "claire.dupont@mode-paris.fr",
    shipping_name: "Claire Dupont",
    shipping_company: "Atelier Dupont SAS",
    shipping_phone: "+33 1 42 68 55 00",
    shipping_address1: "15 Rue de la Paix",
    shipping_city: "Paris",
    shipping_region: "Île-de-France",
    shipping_postal_code: "75002",
    shipping_country_code: "FR",
    shipping_method: "DHL International Express",
    payment_method: "card",
    subtotal: 1200.00,
    subtotal_cents: 120000,
    shipping_cost: 150.00,
    shipping_cents: 15000,
    tax_amount: 0,
    tax_cents: 0,
    discount_amount: 0,
    discount_cents: 0,
    total_amount: 1350.00,
    total_cents: 135000,
    placed_at: "2026-09-12T13:40:00Z",
    created_at: "2026-09-12T13:40:00Z",
    updated_at: "2026-09-12T14:00:00Z",
    items: [
      {
        id: "item_1006_1",
        order_id: "ord_1006",
        product_id: "prd0001",
        product_name: "Essential Cotton Crew T-Shirt",
        product_slug: "essential-cotton-crew-t-shirt",
        product_image_url: "https://images.pexels.com/photos/7658459/pexels-photo-7658459.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        sku: "AYN-TSH-001-WHT-S",
        variant_title: "White / S",
        size: "S",
        color: "White",
        quantity: 150,
        unit_price: 8.00,
        unit_price_cents: 800,
        line_total: 1200.00,
        line_total_cents: 120000,
      },
    ],
    status_events: [
      {
        id: "ev_1006_1",
        order_id: "ord_1006",
        event_type: "order_placed",
        message: "Order placed online.",
        created_at: "2026-09-12T13:40:00Z",
      },
      {
        id: "ev_1006_2",
        order_id: "ord_1006",
        event_type: "payment_failed",
        message: "Payment authentication expired. Customer requested cancellation.",
        created_at: "2026-09-12T14:00:00Z",
      },
    ],
    user: {
      id: 106,
      name: "Claire Dupont",
      email: "claire.dupont@mode-paris.fr",
      company_name: "Atelier Dupont SAS",
    },
  },

  // 7. Shipped High-Volume Sea Freight (Sydney, Australia)
  {
    id: "ord_1007",
    order_number: "AYN-20260914-001172",
    user_id: 107,
    status: "shipped",
    payment_status: "paid",
    fulfillment_status: "shipped",
    currency: "USD",
    email: "liam.connor@aus-merch.com.au",
    shipping_name: "Liam O'Connor",
    shipping_company: "Oceania Merchandising Pty",
    shipping_phone: "+61 2 9876 5432",
    shipping_address1: "88 George Street",
    shipping_city: "Sydney",
    shipping_region: "NSW",
    shipping_postal_code: "2000",
    shipping_country_code: "AU",
    shipping_method: "Ocean Freight Container LCL",
    carrier: "Pacific Shipping Line",
    tracking_number: "BOL-PAC-2026-9812",
    transport_method: "sea",
    destination_port: "Port Botany (SYD)",
    shipping_quote_id: "QT-SEA-2026-0091",
    carrier_status: "Vessel Departed Chittagong Port (CGP)",
    last_carrier_update: "Estimated arrival Port Botany: 21 days",
    shipping_snapshot: {
      provider: "pacific_shipping",
      mode: "sea",
      carrier: "Pacific Shipping Line",
      package_quantity: 800,
      carton_count: 16,
      gross_weight: 320,
      cbm: 1.2,
      destination_port: "Port Botany (SYD)",
    },
    payment_method: "bank_transfer",
    subtotal: 6400.00,
    subtotal_cents: 640000,
    shipping_cost: 540.00,
    shipping_cents: 54000,
    tax_amount: 0,
    tax_cents: 0,
    discount_amount: 0,
    discount_cents: 0,
    total_amount: 6940.00,
    total_cents: 694000,
    placed_at: "2026-09-14T06:15:00Z",
    created_at: "2026-09-14T06:15:00Z",
    updated_at: "2026-09-17T11:00:00Z",
    items: [
      {
        id: "item_1007_1",
        order_id: "ord_1007",
        product_id: "prd0001",
        product_name: "Essential Cotton Crew T-Shirt",
        product_slug: "essential-cotton-crew-t-shirt",
        product_image_url: "https://images.pexels.com/photos/7658459/pexels-photo-7658459.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        sku: "AYN-TSH-001-NVY-L",
        variant_title: "Navy / L",
        size: "L",
        color: "Navy",
        quantity: 800,
        unit_price: 8.00,
        unit_price_cents: 800,
        line_total: 6400.00,
        line_total_cents: 640000,
      },
    ],
    status_events: [
      {
        id: "ev_1007_1",
        order_id: "ord_1007",
        event_type: "order_placed",
        message: "LCL Sea cargo booking created.",
        created_at: "2026-09-14T06:15:00Z",
      },
      {
        id: "ev_1007_2",
        order_id: "ord_1007",
        event_type: "fulfillment_shipped",
        message: "Loaded into container at Chittagong Port (CGP).",
        created_at: "2026-09-17T11:00:00Z",
      },
    ],
    user: {
      id: 107,
      name: "Liam O'Connor",
      email: "liam.connor@aus-merch.com.au",
      company_name: "Oceania Merchandising Pty",
    },
  },

  // 8. Processing Air Express (Toronto, Canada)
  {
    id: "ord_1008",
    order_number: "AYN-20260915-001188",
    user_id: 108,
    status: "processing",
    payment_status: "paid",
    fulfillment_status: "processing",
    currency: "USD",
    email: "rachel.green@torontofits.ca",
    shipping_name: "Rachel Green",
    shipping_company: "Maple Outfitters Co",
    shipping_phone: "+1 416 555 0184",
    shipping_address1: "250 Yonge Street",
    shipping_city: "Toronto",
    shipping_region: "ON",
    shipping_postal_code: "M5B 2L7",
    shipping_country_code: "CA",
    shipping_method: "Aramex Priority Air Express",
    carrier: "Aramex Express Air",
    payment_method: "card",
    subtotal: 1920.00,
    subtotal_cents: 192000,
    shipping_cost: 210.00,
    shipping_cents: 21000,
    tax_amount: 0,
    tax_cents: 0,
    discount_amount: 50.00,
    discount_cents: 5000,
    total_amount: 2080.00,
    total_cents: 208000,
    placed_at: "2026-09-15T15:10:00Z",
    created_at: "2026-09-15T15:10:00Z",
    updated_at: "2026-09-16T08:30:00Z",
    items: [
      {
        id: "item_1008_1",
        order_id: "ord_1008",
        product_id: "prd0002",
        product_name: "Classic Denim Trucker Jacket",
        product_slug: "classic-denim-trucker-jacket",
        product_image_url: "https://images.pexels.com/photos/19490409/pexels-photo-19490409.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        sku: "AYN-JNS-002-BLU-M",
        variant_title: "Indigo / M",
        size: "M",
        color: "Indigo",
        quantity: 60,
        unit_price: 32.00,
        unit_price_cents: 3200,
        line_total: 1920.00,
        line_total_cents: 192000,
      },
    ],
    user: {
      id: 108,
      name: "Rachel Green",
      email: "rachel.green@torontofits.ca",
      company_name: "Maple Outfitters Co",
    },
  },

  // 9. Delivered Order (Retail Customer - Milan, Italy)
  {
    id: "ord_1009",
    order_number: "AYN-20260916-001201",
    user_id: 109,
    status: "delivered",
    payment_status: "paid",
    fulfillment_status: "delivered",
    currency: "USD",
    email: "matteorossi@milano-moda.it",
    shipping_name: "Matteo Rossi",
    shipping_company: "Rossi Sartoria",
    shipping_phone: "+39 02 1234567",
    shipping_address1: "Via Montenapoleone 8",
    shipping_city: "Milano",
    shipping_region: "MI",
    shipping_postal_code: "20121",
    shipping_country_code: "IT",
    shipping_method: "DHL International Express",
    carrier: "DHL Express",
    tracking_number: "AWB-4491823746",
    carrier_status: "Delivered to reception",
    payment_method: "card",
    subtotal: 3200.00,
    subtotal_cents: 320000,
    shipping_cost: 260.00,
    shipping_cents: 26000,
    tax_amount: 0,
    tax_cents: 0,
    discount_amount: 100.00,
    discount_cents: 10000,
    total_amount: 3360.00,
    total_cents: 336000,
    placed_at: "2026-09-16T12:00:00Z",
    created_at: "2026-09-16T12:00:00Z",
    updated_at: "2026-09-19T17:20:00Z",
    items: [
      {
        id: "item_1009_1",
        order_id: "ord_1009",
        product_id: "prd0003",
        product_name: "Linen Long Sleeve Formal Shirt",
        product_slug: "linen-long-sleeve-formal-shirt",
        product_image_url: "https://images.pexels.com/photos/298863/pexels-photo-298863.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        sku: "AYN-SHR-003-SKY-M",
        variant_title: "Sky Blue / M",
        size: "M",
        color: "Sky Blue",
        quantity: 200,
        unit_price: 16.00,
        unit_price_cents: 1600,
        line_total: 3200.00,
        line_total_cents: 320000,
      },
    ],
    user: {
      id: 109,
      name: "Matteo Rossi",
      email: "matteorossi@milano-moda.it",
      company_name: "Rossi Sartoria",
    },
  },

  // 10. Pending Order (Stockists - New York, USA)
  {
    id: "ord_1010",
    order_number: "AYN-20260917-001214",
    user_id: 110,
    status: "pending",
    payment_status: "pending",
    fulfillment_status: "unfulfilled",
    currency: "USD",
    email: "david.miller@manhattanmerch.com",
    shipping_name: "David Miller",
    shipping_company: "Manhattan Merch Group",
    shipping_phone: "+1 212 555 0192",
    shipping_address1: "540 Broadway",
    shipping_address2: "Floor 8",
    shipping_city: "New York",
    shipping_region: "NY",
    shipping_postal_code: "10012",
    shipping_country_code: "US",
    shipping_method: "Aramex Priority Air Express",
    carrier: "Aramex Express Air",
    payment_method: "bank_transfer",
    subtotal: 4800.00,
    subtotal_cents: 480000,
    shipping_cost: 380.00,
    shipping_cents: 38000,
    tax_amount: 0,
    tax_cents: 0,
    discount_amount: 0,
    discount_cents: 0,
    total_amount: 5180.00,
    total_cents: 518000,
    placed_at: "2026-09-17T18:30:00Z",
    created_at: "2026-09-17T18:30:00Z",
    updated_at: "2026-09-17T18:30:00Z",
    items: [
      {
        id: "item_1010_1",
        order_id: "ord_1010",
        product_id: "prd0005",
        product_name: "Oversized Heavyweight Hoodie",
        product_slug: "oversized-heavyweight-hoodie",
        product_image_url: "https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        sku: "AYN-HD-005-BLK-L",
        variant_title: "Jet Black / L",
        size: "L",
        color: "Jet Black",
        quantity: 240,
        unit_price: 20.00,
        unit_price_cents: 2000,
        line_total: 4800.00,
        line_total_cents: 480000,
      },
    ],
    user: {
      id: 110,
      name: "David Miller",
      email: "david.miller@manhattanmerch.com",
      company_name: "Manhattan Merch Group",
    },
  },

  // 11. Confirmed Order (Ready for Packaging - Singapore)
  {
    id: "ord_1011",
    order_number: "AYN-20260918-001229",
    user_id: 111,
    status: "confirmed",
    payment_status: "paid",
    fulfillment_status: "unfulfilled",
    currency: "USD",
    email: "kenji.sato@singaporestyle.sg",
    shipping_name: "Kenji Sato",
    shipping_company: "Apex Distribution Pte",
    shipping_phone: "+65 6789 0123",
    shipping_address1: "10 Marina Boulevard",
    shipping_address2: "#24-01 MBFC Tower 2",
    shipping_city: "Singapore",
    shipping_postal_code: "018983",
    shipping_country_code: "SG",
    shipping_method: "DHL International Express",
    carrier: "DHL Express",
    payment_method: "card",
    subtotal: 2800.00,
    subtotal_cents: 280000,
    shipping_cost: 190.00,
    shipping_cents: 19000,
    tax_amount: 0,
    tax_cents: 0,
    discount_amount: 0,
    discount_cents: 0,
    total_amount: 2990.00,
    total_cents: 299000,
    placed_at: "2026-09-18T05:20:00Z",
    created_at: "2026-09-18T05:20:00Z",
    updated_at: "2026-09-18T09:40:00Z",
    items: [
      {
        id: "item_1011_1",
        order_id: "ord_1011",
        product_id: "prd0006",
        product_name: "Premium Pima Cotton Polo",
        product_slug: "premium-pima-cotton-polo",
        product_image_url: "https://images.pexels.com/photos/1232459/pexels-photo-1232459.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        sku: "AYN-POLO-006-WHT-L",
        variant_title: "White / L",
        size: "L",
        color: "White",
        quantity: 200,
        unit_price: 14.00,
        unit_price_cents: 1400,
        line_total: 2800.00,
        line_total_cents: 280000,
      },
    ],
    user: {
      id: 111,
      name: "Kenji Sato",
      email: "kenji.sato@singaporestyle.sg",
      company_name: "Apex Distribution Pte",
    },
  },

  // 12. Shipped Order with Aramex (Riyadh, Saudi Arabia)
  {
    id: "ord_1012",
    order_number: "AYN-20260918-001235",
    user_id: 112,
    status: "shipped",
    payment_status: "paid",
    fulfillment_status: "shipped",
    currency: "USD",
    email: "faisal.othman@riyadhretail.sa",
    shipping_name: "Faisal Al-Othman",
    shipping_company: "Najd Modern Apparel",
    shipping_phone: "+966 11 456 7890",
    shipping_address1: "King Fahd Road",
    shipping_city: "Riyadh",
    shipping_postal_code: "11564",
    shipping_country_code: "SA",
    shipping_method: "Aramex Priority Air Express",
    carrier: "Aramex Express Air",
    tracking_number: "AWB-7719204918",
    shipment_id: "SHP-ARX-10293",
    carrier_status: "Departed King Khalid Airport Hub",
    direct_tracking_url: "https://www.aramex.com/track/results?shipmentNumber=7719204918",
    payment_method: "bank_transfer",
    subtotal: 5100.00,
    subtotal_cents: 510000,
    shipping_cost: 340.00,
    shipping_cents: 34000,
    tax_amount: 0,
    tax_cents: 0,
    discount_amount: 100.00,
    discount_cents: 10000,
    total_amount: 5340.00,
    total_cents: 534000,
    placed_at: "2026-09-18T08:00:00Z",
    created_at: "2026-09-18T08:00:00Z",
    updated_at: "2026-09-19T14:15:00Z",
    items: [
      {
        id: "item_1012_1",
        order_id: "ord_1012",
        product_id: "prd0001",
        product_name: "Essential Cotton Crew T-Shirt",
        product_slug: "essential-cotton-crew-t-shirt",
        product_image_url: "https://images.pexels.com/photos/7658459/pexels-photo-7658459.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        sku: "AYN-TSH-001-WHT-XL",
        variant_title: "White / XL",
        size: "XL",
        color: "White",
        quantity: 600,
        unit_price: 8.50,
        unit_price_cents: 850,
        line_total: 5100.00,
        line_total_cents: 510000,
      },
    ],
    user: {
      id: 112,
      name: "Faisal Al-Othman",
      email: "faisal.othman@riyadhretail.sa",
      company_name: "Najd Modern Apparel",
    },
  },

  // 13. Processing Order with Custom Payment Verification
  {
    id: "ord_1013",
    order_number: "AYN-20260919-001244",
    user_id: 113,
    status: "processing",
    payment_status: "paid",
    fulfillment_status: "processing",
    currency: "USD",
    email: "elena.rostova@baltictrade.se",
    shipping_name: "Elena Rostova",
    shipping_company: "Nordic Trendsetters AB",
    shipping_phone: "+46 8 123 4567",
    shipping_address1: "Drottninggatan 45",
    shipping_city: "Stockholm",
    shipping_postal_code: "111 51",
    shipping_country_code: "SE",
    shipping_method: "DHL International Express",
    carrier: "DHL Express",
    payment_method: "bank_transfer",
    subtotal: 3840.00,
    subtotal_cents: 384000,
    shipping_cost: 280.00,
    shipping_cents: 28000,
    tax_amount: 0,
    tax_cents: 0,
    discount_amount: 0,
    discount_cents: 0,
    total_amount: 4120.00,
    total_cents: 412000,
    placed_at: "2026-09-19T09:15:00Z",
    created_at: "2026-09-19T09:15:00Z",
    updated_at: "2026-09-19T11:00:00Z",
    items: [
      {
        id: "item_1013_1",
        order_id: "ord_1013",
        product_id: "prd0002",
        product_name: "Classic Denim Trucker Jacket",
        product_slug: "classic-denim-trucker-jacket",
        product_image_url: "https://images.pexels.com/photos/19490409/pexels-photo-19490409.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        sku: "AYN-JNS-002-BLU-L",
        variant_title: "Indigo / L",
        size: "L",
        color: "Indigo",
        quantity: 120,
        unit_price: 32.00,
        unit_price_cents: 3200,
        line_total: 3840.00,
        line_total_cents: 384000,
      },
    ],
    user: {
      id: 113,
      name: "Elena Rostova",
      email: "elena.rostova@baltictrade.se",
      company_name: "Nordic Trendsetters AB",
    },
  },

  // 14. Delivered Retail Order (Rotterdam, Netherlands)
  {
    id: "ord_1014",
    order_number: "AYN-20260919-001250",
    user_id: 114,
    status: "delivered",
    payment_status: "paid",
    fulfillment_status: "delivered",
    currency: "USD",
    email: "lars.van.dijk@dutchthreads.nl",
    shipping_name: "Lars van Dijk",
    shipping_company: "De Rijn Apparel BV",
    shipping_phone: "+31 10 987 6543",
    shipping_address1: "Coolsingel 104",
    shipping_city: "Rotterdam",
    shipping_postal_code: "3011 AG",
    shipping_country_code: "NL",
    shipping_method: "DHL International Express",
    carrier: "DHL Express",
    tracking_number: "AWB-3391827465",
    carrier_status: "Delivered to warehouse loading bay",
    payment_method: "card",
    subtotal: 1760.00,
    subtotal_cents: 176000,
    shipping_cost: 160.00,
    shipping_cents: 16000,
    tax_amount: 0,
    tax_cents: 0,
    discount_amount: 0,
    discount_cents: 0,
    total_amount: 1920.00,
    total_cents: 192000,
    placed_at: "2026-09-19T10:30:00Z",
    created_at: "2026-09-19T10:30:00Z",
    updated_at: "2026-09-20T14:10:00Z",
    items: [
      {
        id: "item_1014_1",
        order_id: "ord_1014",
        product_id: "prd0004",
        product_name: "Chino Relaxed Fit Trousers",
        product_slug: "chino-relaxed-fit-trousers",
        product_image_url: "https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        sku: "AYN-TRU-004-NAV-34",
        variant_title: "Navy / 34",
        size: "34",
        color: "Navy",
        quantity: 110,
        unit_price: 16.00,
        unit_price_cents: 1600,
        line_total: 1760.00,
        line_total_cents: 176000,
      },
    ],
    user: {
      id: 114,
      name: "Lars van Dijk",
      email: "lars.van.dijk@dutchthreads.nl",
      company_name: "De Rijn Apparel BV",
    },
  },

  // 15. Pending Confirmation Order (Awaiting Production Clearance)
  {
    id: "ord_1015",
    order_number: "AYN-20260920-001261",
    user_id: 115,
    status: "pending",
    payment_status: "pending",
    fulfillment_status: "unfulfilled",
    currency: "USD",
    email: "tanya.morozova@vostok-style.kz",
    shipping_name: "Tanya Morozova",
    shipping_company: "Silk Road Trading LLP",
    shipping_phone: "+7 727 123 4567",
    shipping_address1: "Dostyk Avenue 85",
    shipping_city: "Almaty",
    shipping_postal_code: "050010",
    shipping_country_code: "KZ",
    shipping_method: "Aramex Priority Air Express",
    carrier: "Aramex Express Air",
    payment_method: "bank_transfer",
    subtotal: 2400.00,
    subtotal_cents: 240000,
    shipping_cost: 250.00,
    shipping_cents: 25000,
    tax_amount: 0,
    tax_cents: 0,
    discount_amount: 0,
    discount_cents: 0,
    total_amount: 2650.00,
    total_cents: 265000,
    placed_at: "2026-09-20T08:00:00Z",
    created_at: "2026-09-20T08:00:00Z",
    updated_at: "2026-09-20T08:00:00Z",
    items: [
      {
        id: "item_1015_1",
        order_id: "ord_1015",
        product_id: "prd0001",
        product_name: "Essential Cotton Crew T-Shirt",
        product_slug: "essential-cotton-crew-t-shirt",
        product_image_url: "https://images.pexels.com/photos/7658459/pexels-photo-7658459.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        sku: "AYN-TSH-001-GRY-M",
        variant_title: "Grey / M",
        size: "M",
        color: "Grey",
        quantity: 300,
        unit_price: 8.00,
        unit_price_cents: 800,
        line_total: 2400.00,
        line_total_cents: 240000,
      },
    ],
    user: {
      id: 115,
      name: "Tanya Morozova",
      email: "tanya.morozova@vostok-style.kz",
      company_name: "Silk Road Trading LLP",
    },
  },

  // 16. Refunded Order (Sample Batch Returned)
  {
    id: "ord_1016",
    order_number: "AYN-20260920-001270",
    user_id: 116,
    status: "refunded",
    payment_status: "refunded",
    fulfillment_status: "unfulfilled",
    currency: "USD",
    email: "simon.becker@berlinfits.de",
    shipping_name: "Simon Becker",
    shipping_company: "Kreuzberg Fashion Lab",
    shipping_phone: "+49 30 9876 5432",
    shipping_address1: "Oranienstraße 180",
    shipping_city: "Berlin",
    shipping_postal_code: "10999",
    shipping_country_code: "DE",
    shipping_method: "DHL International Express",
    payment_method: "card",
    subtotal: 800.00,
    subtotal_cents: 80000,
    shipping_cost: 110.00,
    shipping_cents: 11000,
    tax_amount: 0,
    tax_cents: 0,
    discount_amount: 0,
    discount_cents: 0,
    total_amount: 910.00,
    total_cents: 91000,
    placed_at: "2026-09-20T10:00:00Z",
    created_at: "2026-09-20T10:00:00Z",
    updated_at: "2026-09-20T15:30:00Z",
    items: [
      {
        id: "item_1016_1",
        order_id: "ord_1016",
        product_id: "prd0001",
        product_name: "Essential Cotton Crew T-Shirt",
        product_slug: "essential-cotton-crew-t-shirt",
        product_image_url: "https://images.pexels.com/photos/7658459/pexels-photo-7658459.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        sku: "AYN-TSH-001-BLK-S",
        variant_title: "Black / S",
        size: "S",
        color: "Black",
        quantity: 100,
        unit_price: 8.00,
        unit_price_cents: 800,
        line_total: 800.00,
        line_total_cents: 80000,
      },
    ],
    status_events: [
      {
        id: "ev_1016_1",
        order_id: "ord_1016",
        event_type: "order_refunded",
        message: "Refund processed to original payment method.",
        created_at: "2026-09-20T15:30:00Z",
      },
    ],
    user: {
      id: 116,
      name: "Simon Becker",
      email: "simon.becker@berlinfits.de",
      company_name: "Kreuzberg Fashion Lab",
    },
  },

  // 17. Processing Order (Wholesale Polo Batch - Cape Town, South Africa)
  {
    id: "ord_1017",
    order_number: "AYN-20260920-001282",
    user_id: 117,
    status: "processing",
    payment_status: "paid",
    fulfillment_status: "processing",
    currency: "USD",
    email: "thabo.nkosi@capetraders.co.za",
    shipping_name: "Thabo Nkosi",
    shipping_company: "Table Mountain Garments",
    shipping_phone: "+27 21 555 0199",
    shipping_address1: "15 Long Street",
    shipping_city: "Cape Town",
    shipping_region: "Western Cape",
    shipping_postal_code: "8001",
    shipping_country_code: "ZA",
    shipping_method: "Aramex Priority Air Express",
    carrier: "Aramex Express Air",
    payment_method: "bank_transfer",
    subtotal: 4200.00,
    subtotal_cents: 420000,
    shipping_cost: 360.00,
    shipping_cents: 36000,
    tax_amount: 0,
    tax_cents: 0,
    discount_amount: 0,
    discount_cents: 0,
    total_amount: 4560.00,
    total_cents: 456000,
    placed_at: "2026-09-20T11:45:00Z",
    created_at: "2026-09-20T11:45:00Z",
    updated_at: "2026-09-20T14:00:00Z",
    items: [
      {
        id: "item_1017_1",
        order_id: "ord_1017",
        product_id: "prd0006",
        product_name: "Premium Pima Cotton Polo",
        product_slug: "premium-pima-cotton-polo",
        product_image_url: "https://images.pexels.com/photos/1232459/pexels-photo-1232459.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        sku: "AYN-POLO-006-BLK-M",
        variant_title: "Black / M",
        size: "M",
        color: "Black",
        quantity: 300,
        unit_price: 14.00,
        unit_price_cents: 1400,
        line_total: 4200.00,
        line_total_cents: 420000,
      },
    ],
    user: {
      id: 117,
      name: "Thabo Nkosi",
      email: "thabo.nkosi@capetraders.co.za",
      company_name: "Table Mountain Garments",
    },
  },

  // 18. Shipped Order with Aramex (Kuala Lumpur, Malaysia)
  {
    id: "ord_1018",
    order_number: "AYN-20260920-001295",
    user_id: 118,
    status: "shipped",
    payment_status: "paid",
    fulfillment_status: "shipped",
    currency: "USD",
    email: "chong.wei@kl-fashion.my",
    shipping_name: "Chong Wei",
    shipping_company: "Nusantara Retail Sdn Bhd",
    shipping_phone: "+60 3 2145 6789",
    shipping_address1: "Jalan Bukit Bintang",
    shipping_address2: "Suite 12-05",
    shipping_city: "Kuala Lumpur",
    shipping_postal_code: "55100",
    shipping_country_code: "MY",
    shipping_method: "Aramex Priority Air Express",
    carrier: "Aramex Express Air",
    tracking_number: "AWB-6629183745",
    carrier_status: "Customs Clearance in Progress at KUL",
    payment_method: "card",
    subtotal: 2560.00,
    subtotal_cents: 256000,
    shipping_cost: 180.00,
    shipping_cents: 18000,
    tax_amount: 0,
    tax_cents: 0,
    discount_amount: 0,
    discount_cents: 0,
    total_amount: 2740.00,
    total_cents: 274000,
    placed_at: "2026-09-20T12:00:00Z",
    created_at: "2026-09-20T12:00:00Z",
    updated_at: "2026-09-20T16:45:00Z",
    items: [
      {
        id: "item_1018_1",
        order_id: "ord_1018",
        product_id: "prd0004",
        product_name: "Chino Relaxed Fit Trousers",
        product_slug: "chino-relaxed-fit-trousers",
        product_image_url: "https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        sku: "AYN-TRU-004-BLK-32",
        variant_title: "Black / 32",
        size: "32",
        color: "Black",
        quantity: 160,
        unit_price: 16.00,
        unit_price_cents: 1600,
        line_total: 2560.00,
        line_total_cents: 256000,
      },
    ],
    user: {
      id: 118,
      name: "Chong Wei",
      email: "chong.wei@kl-fashion.my",
      company_name: "Nusantara Retail Sdn Bhd",
    },
  },

  // 19. Pending Order (Stockist - Doha, Qatar)
  {
    id: "ord_1019",
    order_number: "AYN-20260920-001305",
    user_id: 119,
    status: "pending",
    payment_status: "pending",
    fulfillment_status: "unfulfilled",
    currency: "USD",
    email: "khalid.thani@pearltrading.qa",
    shipping_name: "Khalid Al-Thani",
    shipping_company: "Pearl Apparel Trading",
    shipping_phone: "+974 4412 3456",
    shipping_address1: "Corniche Road",
    shipping_city: "Doha",
    shipping_postal_code: "P.O. Box 9821",
    shipping_country_code: "QA",
    shipping_method: "Aramex Priority Air Express",
    carrier: "Aramex Express Air",
    payment_method: "bank_transfer",
    subtotal: 3600.00,
    subtotal_cents: 360000,
    shipping_cost: 290.00,
    shipping_cents: 29000,
    tax_amount: 0,
    tax_cents: 0,
    discount_amount: 0,
    discount_cents: 0,
    total_amount: 3890.00,
    total_cents: 389000,
    placed_at: "2026-09-20T13:15:00Z",
    created_at: "2026-09-20T13:15:00Z",
    updated_at: "2026-09-20T13:15:00Z",
    items: [
      {
        id: "item_1019_1",
        order_id: "ord_1019",
        product_id: "prd0005",
        product_name: "Oversized Heavyweight Hoodie",
        product_slug: "oversized-heavyweight-hoodie",
        product_image_url: "https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        sku: "AYN-HD-005-NVY-XL",
        variant_title: "Navy / XL",
        size: "XL",
        color: "Navy",
        quantity: 180,
        unit_price: 20.00,
        unit_price_cents: 2000,
        line_total: 3600.00,
        line_total_cents: 360000,
      },
    ],
    user: {
      id: 119,
      name: "Khalid Al-Thani",
      email: "khalid.thani@pearltrading.qa",
      company_name: "Pearl Apparel Trading",
    },
  },

  // 20. Delivered Order (Retail Customer - Madrid, Spain)
  {
    id: "ord_1020",
    order_number: "AYN-20260920-001318",
    user_id: 120,
    status: "delivered",
    payment_status: "paid",
    fulfillment_status: "delivered",
    currency: "USD",
    email: "javier.sanchez@ibero-style.es",
    shipping_name: "Javier Sanchez",
    shipping_company: "Iberia Fashion Collective",
    shipping_phone: "+34 91 234 5678",
    shipping_address1: "Gran Vía 32",
    shipping_city: "Madrid",
    shipping_region: "Madrid",
    shipping_postal_code: "28013",
    shipping_country_code: "ES",
    shipping_method: "DHL International Express",
    carrier: "DHL Express",
    tracking_number: "AWB-2291837465",
    carrier_status: "Delivered to reception",
    payment_method: "card",
    subtotal: 1600.00,
    subtotal_cents: 160000,
    shipping_cost: 170.00,
    shipping_cents: 17000,
    tax_amount: 0,
    tax_cents: 0,
    discount_amount: 0,
    discount_cents: 0,
    total_amount: 1770.00,
    total_cents: 177000,
    placed_at: "2026-09-20T14:00:00Z",
    created_at: "2026-09-20T14:00:00Z",
    updated_at: "2026-09-20T18:30:00Z",
    items: [
      {
        id: "item_1020_1",
        order_id: "ord_1020",
        product_id: "prd0001",
        product_name: "Essential Cotton Crew T-Shirt",
        product_slug: "essential-cotton-crew-t-shirt",
        product_image_url: "https://images.pexels.com/photos/7658459/pexels-photo-7658459.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        sku: "AYN-TSH-001-WHT-M",
        variant_title: "White / M",
        size: "M",
        color: "White",
        quantity: 200,
        unit_price: 8.00,
        unit_price_cents: 800,
        line_total: 1600.00,
        line_total_cents: 160000,
      },
    ],
    user: {
      id: 120,
      name: "Javier Sanchez",
      email: "javier.sanchez@ibero-style.es",
      company_name: "Iberia Fashion Collective",
    },
  },

  // 21. Processing Order (Ready for Export Packing - Seoul, South Korea)
  {
    id: "ord_1021",
    order_number: "AYN-20260920-001325",
    user_id: 121,
    status: "processing",
    payment_status: "paid",
    fulfillment_status: "processing",
    currency: "USD",
    email: "minjun.kim@gangnamfits.kr",
    shipping_name: "Min-jun Kim",
    shipping_company: "Gangnam Threads Inc",
    shipping_phone: "+82 2 1234 5678",
    shipping_address1: "Teheran-ro 152",
    shipping_address2: "Gangnam Finance Center 18F",
    shipping_city: "Seoul",
    shipping_postal_code: "06236",
    shipping_country_code: "KR",
    shipping_method: "DHL International Express",
    carrier: "DHL Express",
    payment_method: "card",
    subtotal: 4480.00,
    subtotal_cents: 448000,
    shipping_cost: 310.00,
    shipping_cents: 31000,
    tax_amount: 0,
    tax_cents: 0,
    discount_amount: 100.00,
    discount_cents: 10000,
    total_amount: 4690.00,
    total_cents: 469000,
    placed_at: "2026-09-20T14:45:00Z",
    created_at: "2026-09-20T14:45:00Z",
    updated_at: "2026-09-20T16:00:00Z",
    items: [
      {
        id: "item_1021_1",
        order_id: "ord_1021",
        product_id: "prd0002",
        product_name: "Classic Denim Trucker Jacket",
        product_slug: "classic-denim-trucker-jacket",
        product_image_url: "https://images.pexels.com/photos/19490409/pexels-photo-19490409.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        sku: "AYN-JNS-002-BLU-S",
        variant_title: "Indigo / S",
        size: "S",
        color: "Indigo",
        quantity: 140,
        unit_price: 32.00,
        unit_price_cents: 3200,
        line_total: 4480.00,
        line_total_cents: 448000,
      },
    ],
    user: {
      id: 121,
      name: "Min-jun Kim",
      email: "minjun.kim@gangnamfits.kr",
      company_name: "Gangnam Threads Inc",
    },
  },

  // 22. Confirmed Order (Ocean Freight LCL - Port of Jebel Ali, UAE)
  {
    id: "ord_1022",
    order_number: "AYN-20260920-001332",
    user_id: 122,
    status: "confirmed",
    payment_status: "paid",
    fulfillment_status: "unfulfilled",
    currency: "USD",
    email: "tariq.aziz@emiratesapparel.ae",
    shipping_name: "Tariq Aziz",
    shipping_company: "Emirates Wholesale Apparel",
    shipping_phone: "+971 4 881 2345",
    shipping_address1: "Jebel Ali Free Zone",
    shipping_address2: "Gate 4, Plot 128",
    shipping_city: "Dubai",
    shipping_postal_code: "P.O. Box 17000",
    shipping_country_code: "AE",
    shipping_method: "Ocean Freight Container LCL",
    carrier: "CMA CGM Ocean Freight",
    transport_method: "sea",
    destination_port: "Port of Jebel Ali (DXB)",
    shipping_quote_id: "QT-SEA-2026-0112",
    shipping_snapshot: {
      provider: "ocean_carrier",
      mode: "sea",
      carrier: "CMA CGM Ocean Freight",
      package_quantity: 1500,
      carton_count: 30,
      gross_weight: 600,
      net_weight: 550,
      cbm: 2.4,
      destination_port: "Port of Jebel Ali (DXB)",
      quoted_shipping_charge: 780.00,
      notes: "Consolidated ocean container rate to Jebel Ali Port.",
    },
    payment_method: "bank_transfer",
    subtotal: 12000.00,
    subtotal_cents: 1200000,
    shipping_cost: 780.00,
    shipping_cents: 78000,
    tax_amount: 0,
    tax_cents: 0,
    discount_amount: 300.00,
    discount_cents: 30000,
    total_amount: 12480.00,
    total_cents: 1248000,
    placed_at: "2026-09-20T15:20:00Z",
    created_at: "2026-09-20T15:20:00Z",
    updated_at: "2026-09-20T17:00:00Z",
    items: [
      {
        id: "item_1022_1",
        order_id: "ord_1022",
        product_id: "prd0001",
        product_name: "Essential Cotton Crew T-Shirt",
        product_slug: "essential-cotton-crew-t-shirt",
        product_image_url: "https://images.pexels.com/photos/7658459/pexels-photo-7658459.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        sku: "AYN-TSH-001-WHT-L",
        variant_title: "White / L",
        size: "L",
        color: "White",
        quantity: 1500,
        unit_price: 8.00,
        unit_price_cents: 800,
        line_total: 12000.00,
        line_total_cents: 1200000,
      },
    ],
    user: {
      id: 122,
      name: "Tariq Aziz",
      email: "tariq.aziz@emiratesapparel.ae",
      company_name: "Emirates Wholesale Apparel",
    },
  },

  // 23. Shipped Order with Aramex (Manama, Bahrain)
  {
    id: "ord_1023",
    order_number: "AYN-20260920-001340",
    user_id: 123,
    status: "shipped",
    payment_status: "paid",
    fulfillment_status: "shipped",
    currency: "USD",
    email: "hassan.darwish@bahraingoods.bh",
    shipping_name: "Hassan Darwish",
    shipping_company: "Dilmun Fashion Retail",
    shipping_phone: "+973 1723 4567",
    shipping_address1: "Government Avenue",
    shipping_city: "Manama",
    shipping_postal_code: "P.O. Box 554",
    shipping_country_code: "BH",
    shipping_method: "Aramex Priority Air Express",
    carrier: "Aramex Express Air",
    tracking_number: "AWB-1192837465",
    shipment_id: "SHP-ARX-10492",
    carrier_status: "Customs Cleared at Bahrain International (BAH)",
    direct_tracking_url: "https://www.aramex.com/track/results?shipmentNumber=1192837465",
    payment_method: "card",
    subtotal: 2100.00,
    subtotal_cents: 210000,
    shipping_cost: 190.00,
    shipping_cents: 19000,
    tax_amount: 0,
    tax_cents: 0,
    discount_amount: 0,
    discount_cents: 0,
    total_amount: 2290.00,
    total_cents: 229000,
    placed_at: "2026-09-20T16:00:00Z",
    created_at: "2026-09-20T16:00:00Z",
    updated_at: "2026-09-20T18:15:00Z",
    items: [
      {
        id: "item_1023_1",
        order_id: "ord_1023",
        product_id: "prd0006",
        product_name: "Premium Pima Cotton Polo",
        product_slug: "premium-pima-cotton-polo",
        product_image_url: "https://images.pexels.com/photos/1232459/pexels-photo-1232459.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        sku: "AYN-POLO-006-SKY-M",
        variant_title: "Sky Blue / M",
        size: "M",
        color: "Sky Blue",
        quantity: 150,
        unit_price: 14.00,
        unit_price_cents: 1400,
        line_total: 2100.00,
        line_total_cents: 210000,
      },
    ],
    user: {
      id: 123,
      name: "Hassan Darwish",
      email: "hassan.darwish@bahraingoods.bh",
      company_name: "Dilmun Fashion Retail",
    },
  },

  // 24. Pending Payment Proof Verification Order (London, UK)
  {
    id: "ord_1024",
    order_number: "AYN-20260920-001351",
    user_id: 124,
    status: "processing",
    payment_status: "pending",
    fulfillment_status: "processing",
    currency: "USD",
    email: "james.wilson@thamesretail.co.uk",
    shipping_name: "James Wilson",
    shipping_company: "Thames Wholesale Garments",
    shipping_phone: "+44 20 7123 4567",
    shipping_address1: "45 Commercial Road",
    shipping_city: "London",
    shipping_postal_code: "E1 1LD",
    shipping_country_code: "GB",
    shipping_method: "Aramex Priority Air Express",
    carrier: "Aramex Express Air",
    payment_method: "bank_transfer",
    payment_proof_url: "https://images.pexels.com/photos/6863183/pexels-photo-6863183.jpeg?auto=compress&cs=tinysrgb&w=800",
    subtotal: 3200.00,
    subtotal_cents: 320000,
    shipping_cost: 260.00,
    shipping_cents: 26000,
    tax_amount: 0,
    tax_cents: 0,
    discount_amount: 0,
    discount_cents: 0,
    total_amount: 3460.00,
    total_cents: 346000,
    placed_at: "2026-09-20T17:10:00Z",
    created_at: "2026-09-20T17:10:00Z",
    updated_at: "2026-09-20T17:30:00Z",
    items: [
      {
        id: "item_1024_1",
        order_id: "ord_1024",
        product_id: "prd0003",
        product_name: "Linen Long Sleeve Formal Shirt",
        product_slug: "linen-long-sleeve-formal-shirt",
        product_image_url: "https://images.pexels.com/photos/298863/pexels-photo-298863.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        sku: "AYN-SHR-003-WHT-M",
        variant_title: "White / M",
        size: "M",
        color: "White",
        quantity: 200,
        unit_price: 16.00,
        unit_price_cents: 1600,
        line_total: 3200.00,
        line_total_cents: 320000,
      },
    ],
    user: {
      id: 124,
      name: "James Wilson",
      email: "james.wilson@thamesretail.co.uk",
      company_name: "Thames Wholesale Garments",
    },
  },

  // 25. Delivered Order (Retail Customer - Dublin, Ireland)
  {
    id: "ord_1025",
    order_number: "AYN-20260920-001362",
    user_id: 125,
    status: "delivered",
    payment_status: "paid",
    fulfillment_status: "delivered",
    currency: "USD",
    email: "patrick.murphy@celticmerch.ie",
    shipping_name: "Patrick Murphy",
    shipping_company: "Celtic Merchandising Ltd",
    shipping_phone: "+353 1 234 5678",
    shipping_address1: "14 Grafton Street",
    shipping_city: "Dublin",
    shipping_postal_code: "D02 XY88",
    shipping_country_code: "IE",
    shipping_method: "DHL International Express",
    carrier: "DHL Express",
    tracking_number: "AWB-9988776655",
    carrier_status: "Delivered to shop front",
    payment_method: "card",
    subtotal: 1600.00,
    subtotal_cents: 160000,
    shipping_cost: 170.00,
    shipping_cents: 17000,
    tax_amount: 0,
    tax_cents: 0,
    discount_amount: 0,
    discount_cents: 0,
    total_amount: 1770.00,
    total_cents: 177000,
    placed_at: "2026-09-20T17:50:00Z",
    created_at: "2026-09-20T17:50:00Z",
    updated_at: "2026-09-20T18:40:00Z",
    items: [
      {
        id: "item_1025_1",
        order_id: "ord_1025",
        product_id: "prd0001",
        product_name: "Essential Cotton Crew T-Shirt",
        product_slug: "essential-cotton-crew-t-shirt",
        product_image_url: "https://images.pexels.com/photos/7658459/pexels-photo-7658459.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        sku: "AYN-TSH-001-BLK-XL",
        variant_title: "Black / XL",
        size: "XL",
        color: "Black",
        quantity: 200,
        unit_price: 8.00,
        unit_price_cents: 800,
        line_total: 1600.00,
        line_total_cents: 160000,
      },
    ],
    user: {
      id: 125,
      name: "Patrick Murphy",
      email: "patrick.murphy@celticmerch.ie",
      company_name: "Celtic Merchandising Ltd",
    },
  },
];
