import { InventoryRecord, Warehouse } from "@/services/admin/inventory.service";

export const INITIAL_MOCK_WAREHOUSES: Warehouse[] = [
  {
    id: 1,
    name: "Dhaka Central Export Hub",
    code: "WH-DHK-01",
    address: "House #33, Road #12, Sector #11, Uttara",
    city: "Dhaka",
    country_code: "BD",
    is_active: true,
    inventories_count: 85,
  },
  {
    id: 2,
    name: "Chittagong Port Export Facility",
    code: "WH-CTG-02",
    address: "Export Processing Zone (EPZ), Agrabad",
    city: "Chittagong",
    country_code: "BD",
    is_active: true,
    inventories_count: 42,
  },
  {
    id: 3,
    name: "Savar Production & Transit Hub",
    code: "WH-SVR-03",
    address: "Plot #14-16, Hemayetpur Industrial Area",
    city: "Savar",
    country_code: "BD",
    is_active: true,
    inventories_count: 28,
  },
];

export const INITIAL_MOCK_INVENTORY: InventoryRecord[] = [
  // ── IN STOCK ITEMS (>= 200) ───────────────────────────────────────────────
  {
    id: 1,
    product_variant_id: 101,
    warehouse_id: 1,
    quantity: 1250,
    reserved_quantity: 150,
    created_at: "2026-01-10T10:00:00Z",
    updated_at: "2026-08-30T14:30:00Z",
    variant: {
      id: 101,
      sku: "LEVIS-TSH-BLK-M",
      title: "Essential Cotton T-Shirt - Black / M",
      size: "M",
      color: "Black",
      stock: 1250,
      product: {
        id: "prd0001",
        name: "Essential Cotton T-Shirt",
        slug: "essential-cotton-t-shirt",
        sku: "LEVIS-TSH-M-BLK-M-PRD0001",
        wholesale_price: 10.0,
        brand: "Levi's",
        category: "T-Shirts",
        images: [
          { id: 1, image_url: "https://images.pexels.com/photos/7658459/pexels-photo-7658459.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
        ],
      },
    },
    warehouse: {
      id: 1,
      name: "Dhaka Central Export Hub",
      code: "WH-DHK-01",
    },
    adjustments: [
      {
        id: 1001,
        previous_quantity: 1000,
        adjustment_amount: 250,
        resulting_quantity: 1250,
        reason: "New export production batch received from sewing line",
        notes: "QA passed AQL 2.5 major standard",
        created_at: "2026-08-28T10:00:00Z",
        admin_user: { id: 1, name: "Ayaan Admin", email: "admin@ayaanclothing.com" },
      },
    ],
  },
  {
    id: 2,
    product_variant_id: 102,
    warehouse_id: 1,
    quantity: 800,
    reserved_quantity: 100,
    created_at: "2026-01-10T10:00:00Z",
    updated_at: "2026-08-30T14:30:00Z",
    variant: {
      id: 102,
      sku: "ADI-HD-GRY-L",
      title: "Heritage Crewneck Sweatshirt - Heather Grey / L",
      size: "L",
      color: "Heather Grey",
      stock: 800,
      product: {
        id: "prd0002",
        name: "Heritage Crewneck Sweatshirt",
        slug: "heritage-crewneck-sweatshirt",
        sku: "ADI-HD-002",
        wholesale_price: 19.5,
        brand: "Adidas",
        category: "Hoodies",
        images: [
          { id: 2, image_url: "https://images.pexels.com/photos/5384445/pexels-photo-5384445.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
        ],
      },
    },
    warehouse: {
      id: 1,
      name: "Dhaka Central Export Hub",
      code: "WH-DHK-01",
    },
    adjustments: [
      {
        id: 1002,
        previous_quantity: 750,
        adjustment_amount: 50,
        resulting_quantity: 800,
        reason: "Physical audit correction",
        created_at: "2026-08-20T11:00:00Z",
        admin_user: { id: 1, name: "Ayaan Admin", email: "admin@ayaanclothing.com" },
      },
    ],
  },
  {
    id: 3,
    product_variant_id: 103,
    warehouse_id: 2,
    quantity: 650,
    reserved_quantity: 80,
    created_at: "2026-02-15T10:00:00Z",
    updated_at: "2026-08-25T16:00:00Z",
    variant: {
      id: 103,
      sku: "CHAMP-HD-NVY-XL",
      title: "Heavyweight Fleece Pullover - Navy / XL",
      size: "XL",
      color: "Navy",
      stock: 650,
      product: {
        id: "prd0003",
        name: "Heavyweight Fleece Pullover Hoodie",
        slug: "heavyweight-fleece-pullover-hoodie",
        sku: "CHAMP-HD-003",
        wholesale_price: 24.0,
        brand: "Champion",
        category: "Hoodies",
        images: [
          { id: 3, image_url: "https://images.pexels.com/photos/6347858/pexels-photo-6347858.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
        ],
      },
    },
    warehouse: {
      id: 2,
      name: "Chittagong Port Export Facility",
      code: "WH-CTG-02",
    },
    adjustments: [],
  },
  {
    id: 4,
    product_variant_id: 104,
    warehouse_id: 1,
    quantity: 520,
    reserved_quantity: 50,
    created_at: "2026-03-01T10:00:00Z",
    updated_at: "2026-08-29T12:00:00Z",
    variant: {
      id: 104,
      sku: "RL-POLO-WHT-M",
      title: "Classic Pique Polo Shirt - White / M",
      size: "M",
      color: "White",
      stock: 520,
      product: {
        id: "prd0004",
        name: "Classic Pique Polo Shirt",
        slug: "classic-pique-polo-shirt",
        sku: "RL-POLO-004",
        wholesale_price: 16.5,
        brand: "Ralph Lauren",
        category: "Polo Shirts",
        images: [
          { id: 4, image_url: "https://images.pexels.com/photos/1232459/pexels-photo-1232459.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
        ],
      },
    },
    warehouse: {
      id: 1,
      name: "Dhaka Central Export Hub",
      code: "WH-DHK-01",
    },
    adjustments: [],
  },
  {
    id: 5,
    product_variant_id: 105,
    warehouse_id: 2,
    quantity: 430,
    reserved_quantity: 40,
    created_at: "2026-03-10T10:00:00Z",
    updated_at: "2026-08-27T09:30:00Z",
    variant: {
      id: 105,
      sku: "ZARA-CHINO-BEI-32",
      title: "Slim Stretch Chino Pants - Beige / 32",
      size: "32",
      color: "Beige",
      stock: 430,
      product: {
        id: "prd0005",
        name: "Slim Stretch Chino Pants",
        slug: "slim-stretch-chino-pants",
        sku: "ZARA-CHINO-005",
        wholesale_price: 18.0,
        brand: "Zara",
        category: "Trousers",
        images: [
          { id: 5, image_url: "https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
        ],
      },
    },
    warehouse: {
      id: 2,
      name: "Chittagong Port Export Facility",
      code: "WH-CTG-02",
    },
    adjustments: [],
  },
  {
    id: 6,
    product_variant_id: 106,
    warehouse_id: 3,
    quantity: 950,
    reserved_quantity: 120,
    created_at: "2026-04-01T10:00:00Z",
    updated_at: "2026-08-31T08:00:00Z",
    variant: {
      id: 106,
      sku: "NIKE-DRY-BLK-L",
      title: "Dry-Tech Active Training Tee - Black / L",
      size: "L",
      color: "Black",
      stock: 950,
      product: {
        id: "prd0006",
        name: "Dry-Tech Active Training Tee",
        slug: "dry-tech-active-training-tee",
        sku: "NIKE-DRY-006",
        wholesale_price: 12.5,
        brand: "Nike",
        category: "Activewear",
        images: [
          { id: 6, image_url: "https://images.pexels.com/photos/4066288/pexels-photo-4066288.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
        ],
      },
    },
    warehouse: {
      id: 3,
      name: "Savar Production & Transit Hub",
      code: "WH-SVR-03",
    },
    adjustments: [],
  },
  {
    id: 7,
    product_variant_id: 107,
    warehouse_id: 1,
    quantity: 340,
    reserved_quantity: 30,
    created_at: "2026-04-15T10:00:00Z",
    updated_at: "2026-08-22T14:15:00Z",
    variant: {
      id: 107,
      sku: "UNIQ-MER-CHA-M",
      title: "Extra Fine Merino Crewneck - Charcoal / M",
      size: "M",
      color: "Charcoal",
      stock: 340,
      product: {
        id: "prd0007",
        name: "Extra Fine Merino Crewneck Sweater",
        slug: "extra-fine-merino-crewneck-sweater",
        sku: "UNIQ-MER-007",
        wholesale_price: 22.0,
        brand: "Uniqlo",
        category: "Sweaters",
        images: [
          { id: 7, image_url: "https://images.pexels.com/photos/45982/pexels-photo-45982.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
        ],
      },
    },
    warehouse: {
      id: 1,
      name: "Dhaka Central Export Hub",
      code: "WH-DHK-01",
    },
    adjustments: [],
  },
  {
    id: 8,
    product_variant_id: 108,
    warehouse_id: 1,
    quantity: 780,
    reserved_quantity: 90,
    created_at: "2026-05-01T10:00:00Z",
    updated_at: "2026-08-26T17:00:00Z",
    variant: {
      id: 108,
      sku: "LEVIS-JNS-IND-34",
      title: "511 Slim Fit Selvedge Denim - Indigo / 34",
      size: "34",
      color: "Indigo",
      stock: 780,
      product: {
        id: "prd0008",
        name: "511 Slim Fit Selvedge Denim",
        slug: "511-slim-fit-selvedge-denim",
        sku: "LEVIS-JNS-008",
        wholesale_price: 26.5,
        brand: "Levi's",
        category: "Pants",
        images: [
          { id: 8, image_url: "https://images.pexels.com/photos/1082529/pexels-photo-1082529.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
        ],
      },
    },
    warehouse: {
      id: 1,
      name: "Dhaka Central Export Hub",
      code: "WH-DHK-01",
    },
    adjustments: [],
  },
  {
    id: 9,
    product_variant_id: 109,
    warehouse_id: 2,
    quantity: 280,
    reserved_quantity: 25,
    created_at: "2026-05-10T10:00:00Z",
    updated_at: "2026-08-24T11:45:00Z",
    variant: {
      id: 109,
      sku: "TNF-WND-RED-L",
      title: "Mountain Light Windbreaker - Summit Red / L",
      size: "L",
      color: "Summit Red",
      stock: 280,
      product: {
        id: "prd0009",
        name: "Mountain Light Windbreaker Jacket",
        slug: "mountain-light-windbreaker-jacket",
        sku: "TNF-WND-009",
        wholesale_price: 32.0,
        brand: "The North Face",
        category: "Jackets",
        images: [
          { id: 9, image_url: "https://images.pexels.com/photos/6770028/pexels-photo-6770028.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
        ],
      },
    },
    warehouse: {
      id: 2,
      name: "Chittagong Port Export Facility",
      code: "WH-CTG-02",
    },
    adjustments: [],
  },
  {
    id: 10,
    product_variant_id: 110,
    warehouse_id: 3,
    quantity: 410,
    reserved_quantity: 50,
    created_at: "2026-05-20T10:00:00Z",
    updated_at: "2026-08-20T15:30:00Z",
    variant: {
      id: 110,
      sku: "COL-CARGO-KHA-32",
      title: "Silver Ridge Cargo Shorts - Khaki / 32",
      size: "32",
      color: "Khaki",
      stock: 410,
      product: {
        id: "prd0010",
        name: "Silver Ridge Cargo Shorts",
        slug: "silver-ridge-cargo-shorts",
        sku: "COL-CARGO-010",
        wholesale_price: 15.0,
        brand: "Columbia",
        category: "Shorts",
        images: [
          { id: 10, image_url: "https://images.pexels.com/photos/6311604/pexels-photo-6311604.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
        ],
      },
    },
    warehouse: {
      id: 3,
      name: "Savar Production & Transit Hub",
      code: "WH-SVR-03",
    },
    adjustments: [],
  },
  {
    id: 11,
    product_variant_id: 111,
    warehouse_id: 1,
    quantity: 600,
    reserved_quantity: 60,
    created_at: "2026-06-01T10:00:00Z",
    updated_at: "2026-08-21T09:00:00Z",
    variant: {
      id: 111,
      sku: "CK-BX-BLK-M",
      title: "Modal Stretch Boxer Brief 3-Pack - Black / M",
      size: "M",
      color: "Black",
      stock: 600,
      product: {
        id: "prd0011",
        name: "Modal Stretch Boxer Brief 3-Pack",
        slug: "modal-stretch-boxer-brief-3-pack",
        sku: "CK-BX-011",
        wholesale_price: 14.5,
        brand: "Calvin Klein",
        category: "Activewear",
        images: [
          { id: 11, image_url: "https://images.pexels.com/photos/428340/pexels-photo-428340.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
        ],
      },
    },
    warehouse: {
      id: 1,
      name: "Dhaka Central Export Hub",
      code: "WH-DHK-01",
    },
    adjustments: [],
  },
  {
    id: 12,
    product_variant_id: 112,
    warehouse_id: 2,
    quantity: 350,
    reserved_quantity: 35,
    created_at: "2026-06-10T10:00:00Z",
    updated_at: "2026-08-19T13:00:00Z",
    variant: {
      id: 112,
      sku: "PUMA-TRK-NVY-L",
      title: "Iconic T7 Track Jacket - Peacoat Navy / L",
      size: "L",
      color: "Peacoat Navy",
      stock: 350,
      product: {
        id: "prd0012",
        name: "Iconic T7 Track Jacket",
        slug: "iconic-t7-track-jacket",
        sku: "PUMA-TRK-012",
        wholesale_price: 25.0,
        brand: "Puma",
        category: "Jackets",
        images: [
          { id: 12, image_url: "https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
        ],
      },
    },
    warehouse: {
      id: 2,
      name: "Chittagong Port Export Facility",
      code: "WH-CTG-02",
    },
    adjustments: [],
  },

  // ── LOW STOCK ITEMS (< 200 and > 0) ──────────────────────────────────────
  {
    id: 13,
    product_variant_id: 113,
    warehouse_id: 1,
    quantity: 145,
    reserved_quantity: 25,
    created_at: "2026-06-15T10:00:00Z",
    updated_at: "2026-08-28T16:00:00Z",
    variant: {
      id: 113,
      sku: "LEVIS-JKT-IND-M",
      title: "Relaxed Trucker Denim Jacket - Vintage Indigo / M",
      size: "M",
      color: "Vintage Indigo",
      stock: 145,
      product: {
        id: "prd0013",
        name: "Relaxed Trucker Denim Jacket",
        slug: "relaxed-trucker-denim-jacket",
        sku: "LEVIS-JKT-013",
        wholesale_price: 34.0,
        brand: "Levi's",
        category: "Jackets",
        images: [
          { id: 13, image_url: "https://images.pexels.com/photos/1040945/pexels-photo-1040945.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
        ],
      },
    },
    warehouse: {
      id: 1,
      name: "Dhaka Central Export Hub",
      code: "WH-DHK-01",
    },
    adjustments: [
      {
        id: 1013,
        previous_quantity: 200,
        adjustment_amount: -55,
        resulting_quantity: 145,
        reason: "Export shipment dispatch to European retail partner",
        notes: "Air freight dispatch via DAC",
        created_at: "2026-08-25T14:00:00Z",
        admin_user: { id: 1, name: "Ayaan Admin", email: "admin@ayaanclothing.com" },
      },
    ],
  },
  {
    id: 14,
    product_variant_id: 114,
    warehouse_id: 1,
    quantity: 85,
    reserved_quantity: 20,
    created_at: "2026-06-20T10:00:00Z",
    updated_at: "2026-08-27T10:20:00Z",
    variant: {
      id: 114,
      sku: "BOSS-POLO-BLK-XL",
      title: "Mercerized Slim Polo - Black / XL",
      size: "XL",
      color: "Black",
      stock: 85,
      product: {
        id: "prd0014",
        name: "Mercerized Cotton Slim Polo",
        slug: "mercerized-cotton-slim-polo",
        sku: "BOSS-POLO-014",
        wholesale_price: 21.0,
        brand: "Hugo Boss",
        category: "Polo Shirts",
        images: [
          { id: 14, image_url: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
        ],
      },
    },
    warehouse: {
      id: 1,
      name: "Dhaka Central Export Hub",
      code: "WH-DHK-01",
    },
    adjustments: [
      {
        id: 1014,
        previous_quantity: 120,
        adjustment_amount: -35,
        resulting_quantity: 85,
        reason: "Wholesale sample dispatch and showroom replenishment",
        created_at: "2026-08-20T09:00:00Z",
        admin_user: { id: 1, name: "Ayaan Admin", email: "admin@ayaanclothing.com" },
      },
    ],
  },
  {
    id: 15,
    product_variant_id: 115,
    warehouse_id: 2,
    quantity: 60,
    reserved_quantity: 15,
    created_at: "2026-07-01T10:00:00Z",
    updated_at: "2026-08-28T11:00:00Z",
    variant: {
      id: 115,
      sku: "PAT-FLC-OAT-L",
      title: "Retro-X Fleece Pullover - Oatmeal / L",
      size: "L",
      color: "Oatmeal",
      stock: 60,
      product: {
        id: "prd0015",
        name: "Retro-X Sherpa Fleece Pullover",
        slug: "retro-x-sherpa-fleece-pullover",
        sku: "PAT-FLC-015",
        wholesale_price: 36.0,
        brand: "Patagonia",
        category: "Sweaters",
        images: [
          { id: 15, image_url: "https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
        ],
      },
    },
    warehouse: {
      id: 2,
      name: "Chittagong Port Export Facility",
      code: "WH-CTG-02",
    },
    adjustments: [],
  },
  {
    id: 16,
    product_variant_id: 116,
    warehouse_id: 2,
    quantity: 120,
    reserved_quantity: 30,
    created_at: "2026-07-05T10:00:00Z",
    updated_at: "2026-08-29T14:40:00Z",
    variant: {
      id: 116,
      sku: "MANGO-BLZ-GRY-40",
      title: "Structured Wool-Blend Blazer - Charcoal Grey / 40",
      size: "40",
      color: "Charcoal Grey",
      stock: 120,
      product: {
        id: "prd0016",
        name: "Structured Wool-Blend Blazer",
        slug: "structured-wool-blend-blazer",
        sku: "MANGO-BLZ-016",
        wholesale_price: 42.0,
        brand: "Mango",
        category: "Jackets",
        images: [
          { id: 16, image_url: "https://images.pexels.com/photos/1342609/pexels-photo-1342609.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
        ],
      },
    },
    warehouse: {
      id: 2,
      name: "Chittagong Port Export Facility",
      code: "WH-CTG-02",
    },
    adjustments: [],
  },
  {
    id: 17,
    product_variant_id: 117,
    warehouse_id: 3,
    quantity: 45,
    reserved_quantity: 10,
    created_at: "2026-07-10T10:00:00Z",
    updated_at: "2026-08-30T10:00:00Z",
    variant: {
      id: 117,
      sku: "AYN-TWL-WHT-ST",
      title: "Luxury Combed Cotton Bath Towel Set - Optical White",
      size: "Set of 4",
      color: "Optical White",
      stock: 45,
      product: {
        id: "prd0017",
        name: "Luxury Combed Cotton Bath Towel Set",
        slug: "luxury-combed-cotton-bath-towel-set",
        sku: "AYN-TWL-017",
        wholesale_price: 18.0,
        brand: "Ayaan Home",
        category: "Towels",
        images: [
          { id: 17, image_url: "https://images.pexels.com/photos/4210860/pexels-photo-4210860.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
        ],
      },
    },
    warehouse: {
      id: 3,
      name: "Savar Production & Transit Hub",
      code: "WH-SVR-03",
    },
    adjustments: [
      {
        id: 1017,
        previous_quantity: 90,
        adjustment_amount: -45,
        resulting_quantity: 45,
        reason: "Emergency stock re-allocation to international export consignment",
        created_at: "2026-08-26T15:00:00Z",
        admin_user: { id: 1, name: "Ayaan Admin", email: "admin@ayaanclothing.com" },
      },
    ],
  },
  {
    id: 18,
    product_variant_id: 118,
    warehouse_id: 1,
    quantity: 180,
    reserved_quantity: 40,
    created_at: "2026-07-15T10:00:00Z",
    updated_at: "2026-08-27T16:15:00Z",
    variant: {
      id: 118,
      sku: "DIESEL-JNS-BLK-32",
      title: "D-Strukt Tapered Distressed Jeans - Jet Black / 32",
      size: "32",
      color: "Jet Black",
      stock: 180,
      product: {
        id: "prd0018",
        name: "D-Strukt Tapered Distressed Jeans",
        slug: "d-strukt-tapered-distressed-jeans",
        sku: "DIESEL-JNS-018",
        wholesale_price: 31.0,
        brand: "Diesel",
        category: "Pants",
        images: [
          { id: 18, image_url: "https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
        ],
      },
    },
    warehouse: {
      id: 1,
      name: "Dhaka Central Export Hub",
      code: "WH-DHK-01",
    },
    adjustments: [],
  },

  // ── OUT OF STOCK ITEMS (=== 0) ───────────────────────────────────────────
  {
    id: 19,
    product_variant_id: 119,
    warehouse_id: 1,
    quantity: 0,
    reserved_quantity: 0,
    created_at: "2026-07-20T10:00:00Z",
    updated_at: "2026-08-30T17:00:00Z",
    variant: {
      id: 119,
      sku: "HM-LINEN-WHT-L",
      title: "Pure European Linen Relaxed Shirt - White / L",
      size: "L",
      color: "White",
      stock: 0,
      product: {
        id: "prd0019",
        name: "Pure European Linen Relaxed Shirt",
        slug: "pure-european-linen-relaxed-shirt",
        sku: "HM-LINEN-019",
        wholesale_price: 16.0,
        brand: "H&M",
        category: "T-Shirts",
        images: [
          { id: 19, image_url: "https://images.pexels.com/photos/297933/pexels-photo-297933.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
        ],
      },
    },
    warehouse: {
      id: 1,
      name: "Dhaka Central Export Hub",
      code: "WH-DHK-01",
    },
    adjustments: [
      {
        id: 1019,
        previous_quantity: 25,
        adjustment_amount: -25,
        resulting_quantity: 0,
        reason: "Batch fully depleted — production rerun queued in weaving line",
        notes: "Next restock scheduled for mid October",
        created_at: "2026-08-30T17:00:00Z",
        admin_user: { id: 1, name: "Ayaan Admin", email: "admin@ayaanclothing.com" },
      },
    ],
  },
  {
    id: 20,
    product_variant_id: 120,
    warehouse_id: 2,
    quantity: 0,
    reserved_quantity: 0,
    created_at: "2026-07-25T10:00:00Z",
    updated_at: "2026-08-31T09:00:00Z",
    variant: {
      id: 120,
      sku: "UA-JGR-BLK-M",
      title: "ArmourFleece Moisture Joggers - Black / M",
      size: "M",
      color: "Black",
      stock: 0,
      product: {
        id: "prd0020",
        name: "ArmourFleece Moisture Joggers",
        slug: "armourfleece-moisture-joggers",
        sku: "UA-JGR-020",
        wholesale_price: 20.0,
        brand: "Under Armour",
        category: "Trousers",
        images: [
          { id: 20, image_url: "https://images.pexels.com/photos/6311604/pexels-photo-6311604.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
        ],
      },
    },
    warehouse: {
      id: 2,
      name: "Chittagong Port Export Facility",
      code: "WH-CTG-02",
    },
    adjustments: [
      {
        id: 1020,
        previous_quantity: 40,
        adjustment_amount: -40,
        resulting_quantity: 0,
        reason: "Full container shipment dispatched to Port of Hamburg",
        created_at: "2026-08-31T09:00:00Z",
        admin_user: { id: 1, name: "Ayaan Admin", email: "admin@ayaanclothing.com" },
      },
    ],
  },
  {
    id: 21,
    product_variant_id: 121,
    warehouse_id: 3,
    quantity: 0,
    reserved_quantity: 0,
    created_at: "2026-08-01T10:00:00Z",
    updated_at: "2026-08-29T11:00:00Z",
    variant: {
      id: 121,
      sku: "TIMB-BMB-OLV-L",
      title: "Weatherbreaker Quilted Bomber - Olive Green / L",
      size: "L",
      color: "Olive Green",
      stock: 0,
      product: {
        id: "prd0021",
        name: "Weatherbreaker Quilted Bomber Jacket",
        slug: "weatherbreaker-quilted-bomber-jacket",
        sku: "TIMB-BMB-021",
        wholesale_price: 38.0,
        brand: "Timberland",
        category: "Jackets",
        images: [
          { id: 21, image_url: "https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
        ],
      },
    },
    warehouse: {
      id: 3,
      name: "Savar Production & Transit Hub",
      code: "WH-SVR-03",
    },
    adjustments: [],
  },

  // ── MORE IN STOCK ITEMS TO SUPPORT 20+ PER PAGE PAGINATION ───────────────
  {
    id: 22,
    product_variant_id: 122,
    warehouse_id: 1,
    quantity: 820,
    reserved_quantity: 110,
    created_at: "2026-08-05T10:00:00Z",
    updated_at: "2026-08-31T11:30:00Z",
    variant: {
      id: 122,
      sku: "VANS-HOOD-BLK-XL",
      title: "Classic Core Fleece Hoodie - Black / XL",
      size: "XL",
      color: "Black",
      stock: 820,
      product: {
        id: "prd0022",
        name: "Classic Core Fleece Hoodie",
        slug: "classic-core-fleece-hoodie",
        sku: "VANS-HOOD-022",
        wholesale_price: 21.5,
        brand: "Vans",
        category: "Hoodies",
        images: [
          { id: 22, image_url: "https://images.pexels.com/photos/6347858/pexels-photo-6347858.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
        ],
      },
    },
    warehouse: {
      id: 1,
      name: "Dhaka Central Export Hub",
      code: "WH-DHK-01",
    },
    adjustments: [],
  },
  {
    id: 23,
    product_variant_id: 123,
    warehouse_id: 2,
    quantity: 490,
    reserved_quantity: 65,
    created_at: "2026-08-10T10:00:00Z",
    updated_at: "2026-08-31T14:10:00Z",
    variant: {
      id: 123,
      sku: "FILA-TRK-NVY-M",
      title: "Vintage Heritage Track Pants - Peacoat Navy / M",
      size: "M",
      color: "Peacoat Navy",
      stock: 490,
      product: {
        id: "prd0023",
        name: "Vintage Heritage Track Pants",
        slug: "vintage-heritage-track-pants",
        sku: "FILA-TRK-023",
        wholesale_price: 17.5,
        brand: "Fila",
        category: "Trousers",
        images: [
          { id: 23, image_url: "https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
        ],
      },
    },
    warehouse: {
      id: 2,
      name: "Chittagong Port Export Facility",
      code: "WH-CTG-02",
    },
    adjustments: [],
  },
  {
    id: 24,
    product_variant_id: 124,
    warehouse_id: 3,
    quantity: 560,
    reserved_quantity: 70,
    created_at: "2026-08-15T10:00:00Z",
    updated_at: "2026-08-31T15:20:00Z",
    variant: {
      id: 124,
      sku: "JJ-OVERSHIRT-OAT-L",
      title: "Heavy Cotton Canvas Overshirt - Oatmeal / L",
      size: "L",
      color: "Oatmeal",
      stock: 560,
      product: {
        id: "prd0024",
        name: "Heavy Cotton Canvas Overshirt",
        slug: "heavy-cotton-canvas-overshirt",
        sku: "JJ-OVERSHIRT-024",
        wholesale_price: 23.0,
        brand: "Jack & Jones",
        category: "Jackets",
        images: [
          { id: 24, image_url: "https://images.pexels.com/photos/1040945/pexels-photo-1040945.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
        ],
      },
    },
    warehouse: {
      id: 3,
      name: "Savar Production & Transit Hub",
      code: "WH-SVR-03",
    },
    adjustments: [],
  },
];
