import { BrandModel } from "@/services/brand.service";

/**
 * Baseline Mock Brands
 * Real apparel brands with official logos, slugs, and active status.
 */
export const INITIAL_MOCK_BRANDS: BrandModel[] = [
  {
    id: "br_ayaan",
    name: "Ayaan",
    slug: "ayaan",
    logo_url: "/logo.png",
    logo: "/logo.png",
    website: "https://ayaanclothing.com",
    sort_order: 1,
    is_active: true,
    products_count: 24,
  },
  {
    id: "br_nike",
    name: "Nike",
    slug: "nike",
    logo_url: "/brands/nike.svg",
    logo: "/brands/nike.svg",
    website: "https://nike.com",
    sort_order: 2,
    is_active: true,
    products_count: 18,
  },
  {
    id: "br_adidas",
    name: "Adidas",
    slug: "adidas",
    logo_url: "/brands/adidas.svg",
    logo: "/brands/adidas.svg",
    website: "https://adidas.com",
    sort_order: 3,
    is_active: true,
    products_count: 16,
  },
  {
    id: "br_levis",
    name: "Levi's",
    slug: "levis",
    logo_url: "/brands/levis.svg",
    logo: "/brands/levis.svg",
    website: "https://levi.com",
    sort_order: 4,
    is_active: true,
    products_count: 15,
  },
  {
    id: "br_puma",
    name: "Puma",
    slug: "puma",
    logo_url: "/brands/puma.svg",
    logo: "/brands/puma.svg",
    website: "https://puma.com",
    sort_order: 5,
    is_active: true,
    products_count: 12,
  },
  {
    id: "br_underarmour",
    name: "Under Armour",
    slug: "under-armour",
    logo_url: "/brands/under-armour.svg",
    logo: "/brands/under-armour.svg",
    website: "https://underarmour.com",
    sort_order: 6,
    is_active: true,
    products_count: 10,
  },
  {
    id: "br_zara",
    name: "Zara",
    slug: "zara",
    logo_url: "/brands/zara.svg",
    logo: "/brands/zara.svg",
    website: "https://zara.com",
    sort_order: 7,
    is_active: true,
    products_count: 14,
  },
  {
    id: "br_hm",
    name: "H&M",
    slug: "hm",
    logo_url: "/brands/hm.svg",
    logo: "/brands/hm.svg",
    website: "https://hm.com",
    sort_order: 8,
    is_active: true,
    products_count: 11,
  },
  {
    id: "br_newbalance",
    name: "New Balance",
    slug: "new-balance",
    logo_url: "/brands/new-balance.svg",
    logo: "/brands/new-balance.svg",
    website: "https://newbalance.com",
    sort_order: 9,
    is_active: true,
    products_count: 8,
  },
  {
    id: "br_calvinklein",
    name: "Calvin Klein",
    slug: "calvin-klein",
    logo_url: "/brands/calvin-klein.svg",
    logo: "/brands/calvin-klein.svg",
    website: "https://calvinklein.com",
    sort_order: 10,
    is_active: true,
    products_count: 9,
  },
  {
    id: "br_reebok",
    name: "Reebok",
    slug: "reebok",
    logo_url: "/brands/reebok.svg",
    logo: "/brands/reebok.svg",
    website: "https://reebok.com",
    sort_order: 11,
    is_active: true,
    products_count: 8,
  },
  {
    id: "br_champion",
    name: "Champion",
    slug: "champion",
    logo_url: "/brands/champion.svg",
    logo: "/brands/champion.svg",
    website: "https://champion.com",
    sort_order: 12,
    is_active: true,
    products_count: 7,
  },
  {
    id: "br_fila",
    name: "Fila",
    slug: "fila",
    logo_url: "/brands/fila.svg",
    logo: "/brands/fila.svg",
    website: "https://fila.com",
    sort_order: 13,
    is_active: true,
    products_count: 6,
  },
  {
    id: "br_vans",
    name: "Vans",
    slug: "vans",
    logo_url: "/brands/vans.svg",
    logo: "/brands/vans.svg",
    website: "https://vans.com",
    sort_order: 14,
    is_active: true,
    products_count: 9,
  },
  {
    id: "br_converse",
    name: "Converse",
    slug: "converse",
    logo_url: "/brands/converse.svg",
    logo: "/brands/converse.svg",
    website: "https://converse.com",
    sort_order: 15,
    is_active: true,
    products_count: 8,
  },
  {
    id: "br_thenorthface",
    name: "The North Face",
    slug: "the-north-face",
    logo_url: "/brands/the-north-face.svg",
    logo: "/brands/the-north-face.svg",
    website: "https://thenorthface.com",
    sort_order: 16,
    is_active: true,
    products_count: 12,
  },
  {
    id: "br_columbia",
    name: "Columbia",
    slug: "columbia",
    logo_url: "/brands/columbia.svg",
    logo: "/brands/columbia.svg",
    website: "https://columbia.com",
    sort_order: 17,
    is_active: true,
    products_count: 7,
  },
  {
    id: "br_patagonia",
    name: "Patagonia",
    slug: "patagonia",
    logo_url: "/brands/patagonia.svg",
    logo: "/brands/patagonia.svg",
    website: "https://patagonia.com",
    sort_order: 18,
    is_active: true,
    products_count: 6,
  },
  {
    id: "br_tommyhilfiger",
    name: "Tommy Hilfiger",
    slug: "tommy-hilfiger",
    logo_url: "/brands/tommy-hilfiger.svg",
    logo: "/brands/tommy-hilfiger.svg",
    website: "https://tommy.com",
    sort_order: 19,
    is_active: true,
    products_count: 11,
  },
  {
    id: "br_hugoboss",
    name: "Hugo Boss",
    slug: "hugo-boss",
    logo_url: "/brands/hugo-boss.svg",
    logo: "/brands/hugo-boss.svg",
    website: "https://hugoboss.com",
    sort_order: 20,
    is_active: true,
    products_count: 8,
  },
  {
    id: "br_ralphlauren",
    name: "Ralph Lauren",
    slug: "ralph-lauren",
    logo_url: "/brands/ralph-lauren.svg",
    logo: "/brands/ralph-lauren.svg",
    website: "https://ralphlauren.com",
    sort_order: 21,
    is_active: true,
    products_count: 10,
  },
  {
    id: "br_uniqlo",
    name: "Uniqlo",
    slug: "uniqlo",
    logo_url: "/brands/uniqlo.svg",
    logo: "/brands/uniqlo.svg",
    website: "https://uniqlo.com",
    sort_order: 22,
    is_active: true,
    products_count: 14,
  },
  {
    id: "br_diesel",
    name: "Diesel",
    slug: "diesel",
    logo_url: "/brands/diesel.svg",
    logo: "/brands/diesel.svg",
    website: "https://diesel.com",
    sort_order: 23,
    is_active: true,
    products_count: 6,
  },
  {
    id: "br_timberland",
    name: "Timberland",
    slug: "timberland",
    logo_url: "/brands/timberland.svg",
    logo: "/brands/timberland.svg",
    website: "https://timberland.com",
    sort_order: 24,
    is_active: true,
    products_count: 7,
  },
  {
    id: "br_mango",
    name: "Mango",
    slug: "mango",
    logo_url: "/brands/mango.svg",
    logo: "/brands/mango.svg",
    website: "https://mango.com",
    sort_order: 25,
    is_active: true,
    products_count: 9,
  },
  {
    id: "br_jackjones",
    name: "Jack & Jones",
    slug: "jack-and-jones",
    logo_url: "/brands/jack-and-jones.svg",
    logo: "/brands/jack-and-jones.svg",
    website: "https://jackjones.com",
    sort_order: 26,
    is_active: true,
    products_count: 8,
  },
];
