import { RfqRecord } from "@/types/b2b";

export const INITIAL_MOCK_RFQS: RfqRecord[] = [
  {
    id: "rfq_demo_customer_999",
    rfqNumber: "RFQ-2026-000999",
    userId: "999",
    buyerName: "Demo Customer",
    buyerEmail: "customer@ayaan-demo.local",
    buyerPhone: "+1-555-0199",
    companyName: "Ayaan Commercial Demo Corp",
    businessType: "Wholesale Distributor",
    website: "https://ayaanclothing.com",
    taxNumber: "US-DEMO-99901",
    destinationCountry: "United States",
    destinationCity: "Springfield",
    shippingPort: "Port of Seattle / Sea-Tac Air Cargo",
    targetDeliveryDate: "2026-11-15",
    requestTitle: "250 Luxury Knitwear & T-Shirts Assortment",
    generalNotes: "Need assorted sizes and colors for Fall 2026 boutique opening.",
    status: "UNDER_REVIEW",
    items: [
      {
        id: "rfq_item_999_1",
        productId: "prd0001",
        productName: "Essential Cotton T-Shirt",
        productSlug: "essential-cotton-t-shirt",
        brand: "Levi's",
        sku: "LEVIS-TSH-M-BLK-M-PRD0001",
        image: "https://images.pexels.com/photos/7658459/pexels-photo-7658459.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        selectedColor: "Black",
        selectedSize: "M",
        quantity: 250,
        moq: 5,
        unitPrice: 12.00,
        targetPrice: 10.00,
        buyerNotes: "High density polybag retail packaging required.",
      },
    ],
    messages: [
      {
        id: "msg_999_1",
        rfqId: "rfq_demo_customer_999",
        senderRole: "buyer",
        senderName: "Demo Customer",
        message: "Hello Ayaan team, please provide FOB shipping rates and export lead time.",
        createdAt: "2026-09-24T10:00:00.000Z",
      },
      {
        id: "msg_999_2",
        rfqId: "rfq_demo_customer_999",
        senderRole: "sales",
        senderName: "Ayaan Export Sales",
        message: "Thank you! We have reviewed your request and prepared official Quotation QT-2026-000999 for your account.",
        createdAt: "2026-09-24T10:30:00.000Z",
      },
    ],
    history: [
      {
        id: "hist_999_1",
        rfqId: "rfq_demo_customer_999",
        status: "SUBMITTED",
        actorName: "Demo Customer",
        note: "Initial RFQ submitted by customer",
        createdAt: "2026-09-24T10:00:00.000Z",
      },
      {
        id: "hist_999_2",
        rfqId: "rfq_demo_customer_999",
        status: "UNDER_REVIEW",
        actorName: "Export Desk",
        note: "Assigned to North America export division",
        createdAt: "2026-09-24T10:15:00.000Z",
      },
    ],
    createdAt: "2026-09-24T10:00:00.000Z",
    updatedAt: "2026-09-24T10:30:00.000Z",
  },
  {
    id: "rfq_demo_101",
    rfqNumber: "RFQ-2026-000101",
    userId: "usr_101",
    buyerName: "Tariq Al-Mansoor",
    buyerEmail: "tariq@gulfapparel.ae",
    buyerPhone: "+971 50 123 4567",
    companyName: "Gulf Apparel Trading LLC",
    businessType: "Wholesale Distributor",
    website: "https://gulfapparel.ae",
    taxNumber: "AE-TRN-100234567",
    destinationCountry: "United Arab Emirates",
    destinationCity: "Dubai",
    shippingPort: "Jebel Ali Port / Dubai International Airport",
    targetDeliveryDate: "2026-10-15",
    requestTitle: "500 Nike T-Shirts for UAE Retail Network",
    generalNotes: "Need assorted sizes (M: 200, L: 200, XL: 100). Please quote FOB Chittagong with optional air express sample dispatch.",
    status: "UNDER_REVIEW",
    items: [
      {
        id: "rfq_item_101_1",
        productId: "prd0001",
        productName: "Essential Cotton T-Shirt",
        productSlug: "essential-cotton-t-shirt",
        brand: "Levi's",
        sku: "LEVIS-TSH-M-BLK-M-PRD0001",
        image: "https://images.pexels.com/photos/7658459/pexels-photo-7658459.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        selectedColor: "Black",
        selectedSize: "Assorted (M, L, XL)",
        quantity: 500,
        moq: 50,
        unitPrice: 12.00,
        targetPrice: 10.50,
        buyerNotes: "High density polybag retail packaging required.",
      },
    ],
    messages: [
      {
        id: "msg_101_1",
        rfqId: "rfq_demo_101",
        senderRole: "buyer",
        senderName: "Tariq Al-Mansoor",
        message: "Hello Ayaan team, we are looking for a reliable shipment of 500 pcs to Dubai. Please confirm lead time and available export certifications.",
        createdAt: "2026-09-23T08:30:00.000Z",
      },
      {
        id: "msg_101_2",
        rfqId: "rfq_demo_101",
        senderRole: "sales",
        senderName: "Ayaan Export Sales",
        message: "Thank you for the inquiry Tariq! Production lead time is 14 days. We are preparing your official quotation with FOB Chittagong pricing now.",
        createdAt: "2026-08-24T15:10:00Z",
      },
    ],
    history: [
      {
        id: "hist_101_1",
        rfqId: "rfq_demo_101",
        status: "SUBMITTED",
        actorName: "Tariq Al-Mansoor",
        note: "Initial RFQ submitted by buyer",
        createdAt: "2026-08-24T14:30:00Z",
      },
      {
        id: "hist_101_2",
        rfqId: "rfq_demo_101",
        status: "UNDER_REVIEW",
        actorName: "Sales Admin",
        note: "Assigned to Middle East export desk",
        createdAt: "2026-08-24T15:00:00Z",
      },
    ],
    createdAt: "2026-08-24T14:30:00Z",
    updatedAt: "2026-09-23T09:15:00.000Z",
  },
  {
    id: "rfq_demo_102",
    rfqNumber: "RFQ-2026-000102",
    userId: "usr_102",
    buyerName: "Marcus Vance",
    buyerEmail: "buyer@ayaanclothing.com",
    buyerPhone: "+44 20 7946 0912",
    companyName: "Vance & Co Retail Ltd",
    businessType: "Wholesaler",
    website: "https://vancestyle.co.uk",
    taxNumber: "GB987654321",
    destinationCountry: "United Kingdom",
    destinationCity: "London",
    shippingPort: "Port of Felixstowe / Heathrow Airport",
    targetDeliveryDate: "2026-10-15",
    requestTitle: "Autumn Knitwear & Heavyweight Hoodies Bulk Inquiry",
    generalNotes: "Looking for custom neck label branding and export carton polybags. Fast air sample dispatch requested.",
    status: "QUOTATION_PREPARED",
    items: [
      {
        id: "rfq_item_102_1",
        productId: "prd0001",
        productName: "Essential Cotton T-Shirt",
        productSlug: "essential-cotton-t-shirt",
        brand: "Levi's",
        sku: "LEVIS-TSH-M-BLK-M-PRD0001",
        image: "https://images.pexels.com/photos/7658459/pexels-photo-7658459.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        selectedColor: "Black & White",
        selectedSize: "Run S-2XL",
        quantity: 500,
        moq: 50,
        unitPrice: 8.00,
        targetPrice: 7.50,
        buyerNotes: "Color breakdown: 300 Black, 200 White. Size run S-2XL.",
      },
    ],
    messages: [
      {
        id: "msg_102_1",
        rfqId: "rfq_demo_102",
        senderName: "Marcus Vance",
        senderRole: "buyer",
        message: "Can you provide quotation with CIF London air freight?",
        createdAt: "2026-09-23T11:15:00.000Z",
      },
      {
        id: "msg_102_2",
        rfqId: "rfq_demo_102",
        senderName: "Ayaan Admin",
        senderRole: "admin",
        message: "Quotation QT-2026-000102 generated with discounted Aramex priority air rates.",
        createdAt: "2026-08-21T14:30:00Z",
      },
    ],
    history: [
      {
        id: "hist_102_1",
        rfqId: "rfq_demo_102",
        status: "SUBMITTED",
        actorName: "Marcus Vance",
        note: "Initial RFQ submitted by buyer",
        createdAt: "2026-08-20T09:30:00Z",
      },
      {
        id: "hist_102_2",
        rfqId: "rfq_demo_102",
        status: "QUOTATION_PREPARED",
        actorName: "Ayaan Admin",
        note: "Quotation prepared and sent to buyer",
        createdAt: "2026-08-21T14:00:00Z",
      },
    ],
    quotationId: "qt_demo_102",
    createdAt: "2026-08-20T09:30:00Z",
    updatedAt: "2026-09-23T12:00:00.000Z",
  },
  {
    id: "rfq_demo_103",
    rfqNumber: "RFQ-2026-000103",
    userId: "usr_103",
    buyerName: "Sarah Jenkins",
    buyerEmail: "testuser@example.com",
    buyerPhone: "+1-555-0199",
    companyName: "Jenkins Apparel Boutique",
    businessType: "Boutique Chain",
    website: "https://jenkinsboutique.com",
    taxNumber: "US-EIN-98-7654321",
    destinationCountry: "United States",
    destinationCity: "Los Angeles",
    shippingPort: "Port of Long Beach / LAX Airport",
    targetDeliveryDate: "2026-11-01",
    requestTitle: "Denim Jackets & Vintage Washed Pullovers Inquiry",
    generalNotes: "Initial trial batch for retail chain launch in California. Please provide sample approval schedule.",
    status: "SUBMITTED",
    items: [
      {
        id: "rfq_item_103_1",
        productId: "prd0002",
        productName: "Classic Denim Jacket",
        productSlug: "classic-denim-jacket",
        brand: "Ayaan",
        sku: "AYN-JNS-002",
        image: "https://images.pexels.com/photos/19490409/pexels-photo-19490409.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        selectedColor: "Vintage Blue",
        selectedSize: "Assorted (S-XL)",
        quantity: 200,
        moq: 50,
        unitPrice: 32.00,
        targetPrice: 30.00,
        buyerNotes: "Assorted sizes: S:40, M:80, L:60, XL:20",
      },
    ],
    messages: [
      {
        id: "msg_103_1",
        rfqId: "rfq_demo_103",
        senderRole: "buyer",
        senderName: "Sarah Jenkins",
        message: "Hi! We are expanding our West Coast stores and would like to review fabric swatches for the denim jackets.",
        createdAt: "2026-09-23T14:45:00.000Z",
      },
    ],
    history: [
      {
        id: "hist_103_1",
        rfqId: "rfq_demo_103",
        status: "SUBMITTED",
        actorName: "Sarah Jenkins",
        note: "Submitted RFQ for denim jacket trial run",
        createdAt: "2026-08-29T11:15:00Z",
      },
    ],
    createdAt: "2026-08-29T11:15:00Z",
    updatedAt: "2026-09-23T15:10:00.000Z",
  },
  {
    id: "rfq_demo_104",
    rfqNumber: "RFQ-2026-000104",
    userId: "usr_104",
    buyerName: "Kenji Sato",
    buyerEmail: "k.sato@tokyostreetwear.jp",
    buyerPhone: "+81 3 5555 0142",
    companyName: "Tokyo Streetwear Collective",
    businessType: "Wholesaler",
    website: "https://tokyostreetwear.jp",
    taxNumber: "JP9876543210123",
    destinationCountry: "Japan",
    destinationCity: "Tokyo",
    shippingPort: "Tokyo Port / Narita Airport",
    targetDeliveryDate: "2026-11-10",
    requestTitle: "Oversized Streetwear Tees for Harajuku Retail",
    generalNotes: "Japanese fiber content tags and care instructions must be printed in Japanese.",
    status: "QUOTATION_PREPARED",
    items: [
      {
        id: "rfq_item_104_1",
        productId: "prd0006",
        productName: "Oversized Streetwear Graphic Tee",
        productSlug: "oversized-streetwear-graphic-tee",
        brand: "Stüssy",
        sku: "STUSSY-TEE-006",
        image: "https://images.pexels.com/photos/8532616/pexels-photo-8532616.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        selectedColor: "Vintage Washed Black",
        selectedSize: "L",
        quantity: 600,
        moq: 50,
        unitPrice: 15.00,
        targetPrice: 13.50,
        buyerNotes: "Heavyweight 240 GSM single jersey cotton required.",
      },
    ],
    messages: [
      {
        id: "msg_104_1",
        rfqId: "rfq_demo_104",
        senderRole: "buyer",
        senderName: "Kenji Sato",
        message: "Konichiwa! Can you verify colorfastness grade 4 or above?",
        createdAt: "2026-09-23T17:20:00.000Z",
      },
      {
        id: "msg_104_2",
        rfqId: "rfq_demo_104",
        senderRole: "admin",
        senderName: "Ayaan QC Desk",
        message: "Yes Kenji-san! All our dyes are reactive and tested to ISO 105-C06 Grade 4+. Quotation is prepared.",
        createdAt: "2026-08-26T16:00:00Z",
      },
    ],
    history: [
      {
        id: "hist_104_1",
        rfqId: "rfq_demo_104",
        status: "SUBMITTED",
        actorName: "Kenji Sato",
        note: "Submitted inquiry for 600 heavy graphic tees",
        createdAt: "2026-08-25T07:45:00Z",
      },
      {
        id: "hist_104_2",
        rfqId: "rfq_demo_104",
        status: "QUOTATION_PREPARED",
        actorName: "Ayaan Admin",
        note: "Quotation QT-2026-000104 prepared and submitted",
        createdAt: "2026-08-26T16:00:00Z",
      },
    ],
    quotationId: "qt_demo_104",
    createdAt: "2026-08-25T07:45:00Z",
    updatedAt: "2026-09-23T17:45:00.000Z",
  },
  {
    id: "rfq_demo_105",
    rfqNumber: "RFQ-2026-000105",
    userId: "usr_105",
    buyerName: "Chloe Dubois",
    buyerEmail: "chloe@maisondemodeparis.fr",
    buyerPhone: "+33 1 42 68 55 00",
    companyName: "Maison de Mode Paris",
    businessType: "Fashion Retailer",
    website: "https://maisondemodeparis.fr",
    taxNumber: "FR87654321098",
    destinationCountry: "France",
    destinationCity: "Paris",
    shippingPort: "Port of Le Havre / CDG Airport",
    targetDeliveryDate: "2026-11-20",
    requestTitle: "Oxford Shirts & Formal Attire Winter Collection",
    generalNotes: "Need European standard fitting. Please quote FOB Chittagong with 100% combed cotton.",
    status: "NEGOTIATION",
    items: [
      {
        id: "rfq_item_105_1",
        productId: "prd0008",
        productName: "Oxford Button-Down Shirt",
        productSlug: "oxford-button-down-shirt",
        brand: "Brooks Brothers",
        sku: "BB-OXF-008",
        image: "https://images.pexels.com/photos/297933/pexels-photo-297933.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        selectedColor: "Classic White",
        selectedSize: "M",
        quantity: 400,
        moq: 50,
        unitPrice: 20.00,
        targetPrice: 18.00,
        buyerNotes: "Mother of pearl finish buttons requested.",
      },
    ],
    messages: [
      {
        id: "msg_105_1",
        rfqId: "rfq_demo_105",
        senderRole: "buyer",
        senderName: "Chloe Dubois",
        message: "Bonjour. Can we negotiate the price down by $1.50 per piece for a repeat 400-piece order?",
        createdAt: "2026-09-22T09:10:00.000Z",
      },
      {
        id: "msg_105_2",
        rfqId: "rfq_demo_105",
        senderRole: "sales",
        senderName: "Ayaan Export Sales",
        message: "Bonjour Chloe! We can offer $18.00/unit if payment is structured with Net 30 days. Revision sent.",
        createdAt: "2026-08-27T14:20:00Z",
      },
    ],
    history: [
      {
        id: "hist_105_1",
        rfqId: "rfq_demo_105",
        status: "SUBMITTED",
        actorName: "Chloe Dubois",
        note: "Initial RFQ created",
        createdAt: "2026-08-23T14:00:00Z",
      },
      {
        id: "hist_105_2",
        rfqId: "rfq_demo_105",
        status: "NEGOTIATION",
        actorName: "Sales Admin",
        note: "Negotiation opened regarding volume pricing discount",
        createdAt: "2026-08-27T14:20:00Z",
      },
    ],
    quotationId: "qt_demo_105",
    createdAt: "2026-08-23T14:00:00Z",
    updatedAt: "2026-09-22T10:00:00.000Z",
  },
  {
    id: "rfq_demo_106",
    rfqNumber: "RFQ-2026-000106",
    userId: "usr_106",
    buyerName: "Liam O'Connor",
    buyerEmail: "l.oconnor@emeraldretail.ie",
    buyerPhone: "+353 1 496 0123",
    companyName: "Emerald Retail Group",
    businessType: "Department Store",
    website: "https://emeraldretail.ie",
    taxNumber: "IE9876543W",
    destinationCountry: "Ireland",
    destinationCity: "Dublin",
    shippingPort: "Dublin Port",
    targetDeliveryDate: "2026-12-01",
    requestTitle: "Heavyweight Fleece Hoodies for Autumn Stocking",
    generalNotes: "High density embroidery on chest. Heavy 380 GSM brushed back fleece.",
    status: "SUBMITTED",
    items: [
      {
        id: "rfq_item_106_1",
        productId: "prd0004",
        productName: "Heavyweight Fleece Hoodie",
        productSlug: "heavyweight-fleece-hoodie",
        brand: "Champion",
        sku: "CHAMP-HD-004",
        image: "https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        selectedColor: "Heather Grey",
        selectedSize: "L",
        quantity: 300,
        moq: 50,
        unitPrice: 22.00,
        targetPrice: 19.50,
        buyerNotes: "Double-lined hood with metal eyelets and thick drawstrings.",
      },
    ],
    messages: [],
    history: [
      {
        id: "hist_106_1",
        rfqId: "rfq_demo_106",
        status: "SUBMITTED",
        actorName: "Liam O'Connor",
        note: "RFQ submitted for Dublin department store restocking",
        createdAt: "2026-09-22T13:30:00.000Z",
      },
    ],
    createdAt: "2026-08-28T09:00:00Z",
    updatedAt: "2026-09-22T14:15:00.000Z",
  },
  {
    id: "rfq_demo_107",
    rfqNumber: "RFQ-2026-000107",
    userId: "usr_107",
    buyerName: "Matteo Rossi",
    buyerEmail: "m.rossi@milanoaltamoda.it",
    buyerPhone: "+39 02 8765 4321",
    companyName: "Milano Alta Moda",
    businessType: "Wholesale Boutique",
    website: "https://milanoaltamoda.it",
    taxNumber: "IT09876543210",
    destinationCountry: "Italy",
    destinationCity: "Milan",
    shippingPort: "Port of Genoa / Milan Malpensa",
    targetDeliveryDate: "2026-10-30",
    requestTitle: "Premium Pima Cotton Polos for Italian Spring Pre-order",
    generalNotes: "100% Peruvian long-staple pima cotton. Custom collar tipping.",
    status: "ACCEPTED",
    items: [
      {
        id: "rfq_item_107_1",
        productId: "prd0003",
        productName: "Premium Pima Cotton Polo",
        productSlug: "premium-pima-cotton-polo",
        brand: "Ralph Lauren",
        sku: "RL-POLO-003",
        image: "https://images.pexels.com/photos/1232459/pexels-photo-1232459.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        selectedColor: "Navy Blue",
        selectedSize: "L",
        quantity: 500,
        moq: 50,
        unitPrice: 16.00,
        targetPrice: 14.50,
        buyerNotes: "Custom collar tipping in contrasting white.",
      },
    ],
    messages: [
      {
        id: "msg_107_1",
        rfqId: "rfq_demo_107",
        senderRole: "buyer",
        senderName: "Matteo Rossi",
        message: "We have reviewed and accepted Quotation QT-2026-000107. Please generate Proforma Invoice for 50% deposit.",
        createdAt: "2026-09-22T18:45:00.000Z",
      },
    ],
    history: [
      {
        id: "hist_107_1",
        rfqId: "rfq_demo_107",
        status: "SUBMITTED",
        actorName: "Matteo Rossi",
        createdAt: "2026-08-21T10:00:00Z",
      },
      {
        id: "hist_107_2",
        rfqId: "rfq_demo_107",
        status: "QUOTATION_PREPARED",
        actorName: "Ayaan Admin",
        note: "Quotation issued to buyer",
        createdAt: "2026-08-22T08:00:00Z",
      },
      {
        id: "hist_107_3",
        rfqId: "rfq_demo_107",
        status: "ACCEPTED",
        actorName: "Matteo Rossi",
        note: "Buyer approved quotation terms",
        createdAt: "2026-08-23T11:45:00Z",
      },
    ],
    quotationId: "qt_demo_107",
    createdAt: "2026-08-21T10:00:00Z",
    updatedAt: "2026-09-22T19:00:00.000Z",
  },
  {
    id: "rfq_demo_108",
    rfqNumber: "RFQ-2026-000108",
    userId: "usr_108",
    buyerName: "Sofia Lindqvist",
    buyerEmail: "sofia@nordiclifestyle.se",
    buyerPhone: "+46 8 123 4567",
    companyName: "Nordic Lifestyle AB",
    businessType: "Wholesaler",
    website: "https://nordiclifestyle.se",
    taxNumber: "SE556123456701",
    destinationCountry: "Sweden",
    destinationCity: "Stockholm",
    shippingPort: "Port of Gothenburg / Arlanda Airport",
    targetDeliveryDate: "2026-11-15",
    requestTitle: "Sustainable Organic Cotton Hoodies for Scandinavia",
    generalNotes: "GOTS certificate copy required with shipping documents.",
    status: "QUOTATION_PREPARED",
    items: [
      {
        id: "rfq_item_108_1",
        productId: "prd0004",
        productName: "Heavyweight Fleece Hoodie",
        productSlug: "heavyweight-fleece-hoodie",
        brand: "Champion",
        sku: "CHAMP-HD-004",
        image: "https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        selectedColor: "Charcoal Black",
        selectedSize: "XL",
        quantity: 350,
        moq: 50,
        unitPrice: 24.00,
        targetPrice: 21.00,
        buyerNotes: "Organic woven neck labels with recycled polyester thread.",
      },
    ],
    messages: [
      {
        id: "msg_108_1",
        rfqId: "rfq_demo_108",
        senderRole: "admin",
        senderName: "Ayaan Export Sales",
        message: "Hej Sofia! Quotation QT-2026-000108 has been issued with DDP Stockholm terms.",
        createdAt: "2026-09-21T10:20:00.000Z",
      },
    ],
    history: [
      {
        id: "hist_108_1",
        rfqId: "rfq_demo_108",
        status: "SUBMITTED",
        actorName: "Sofia Lindqvist",
        createdAt: "2026-08-26T15:00:00Z",
      },
      {
        id: "hist_108_2",
        rfqId: "rfq_demo_108",
        status: "QUOTATION_PREPARED",
        actorName: "Sales Admin",
        note: "Quotation issued with DDP delivery",
        createdAt: "2026-08-27T09:00:00Z",
      },
    ],
    quotationId: "qt_demo_108",
    createdAt: "2026-08-26T15:00:00Z",
    updatedAt: "2026-09-21T11:00:00.000Z",
  },
  {
    id: "rfq_demo_109",
    rfqNumber: "RFQ-2026-000109",
    userId: "usr_109",
    buyerName: "David Zhang",
    buyerEmail: "d.zhang@pacificrimtrading.ca",
    buyerPhone: "+1 604 555 0188",
    companyName: "Pacific Rim Trading",
    businessType: "Distributor",
    destinationCountry: "Canada",
    destinationCity: "Vancouver",
    shippingPort: "Port of Vancouver",
    targetDeliveryDate: "2026-11-25",
    requestTitle: "High-volume basic crewneck tee program (800 pcs)",
    generalNotes: "Long term seasonal reorder expected if first batch passes quality inspection.",
    status: "SUBMITTED",
    items: [
      {
        id: "rfq_item_109_1",
        productId: "prd0001",
        productName: "Essential Cotton T-Shirt",
        productSlug: "essential-cotton-t-shirt",
        brand: "Levi's",
        sku: "LEVIS-TSH-M-BLK-M-PRD0001",
        image: "https://images.pexels.com/photos/7658459/pexels-photo-7658459.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        selectedColor: "Navy / White / Olive",
        selectedSize: "S-2XL",
        quantity: 800,
        moq: 50,
        unitPrice: 10.00,
        targetPrice: 8.75,
      },
    ],
    messages: [],
    history: [
      {
        id: "hist_109_1",
        rfqId: "rfq_demo_109",
        status: "SUBMITTED",
        actorName: "David Zhang",
        createdAt: "2026-09-20T15:15:00.000Z",
      },
    ],
    createdAt: "2026-08-29T16:00:00Z",
    updatedAt: "2026-09-20T16:00:00.000Z",
  },
  {
    id: "rfq_demo_110",
    rfqNumber: "RFQ-2026-000110",
    userId: "usr_110",
    buyerName: "Amara Okafor",
    buyerEmail: "amara@lagospremier.ng",
    buyerPhone: "+234 1 234 5678",
    companyName: "Lagos Premier Apparel",
    businessType: "Wholesale Boutique",
    destinationCountry: "Nigeria",
    destinationCity: "Lagos",
    shippingPort: "Apapa Port / Murtala Muhammed Airport",
    targetDeliveryDate: "2026-12-15",
    requestTitle: "Chino trousers shipment to West Africa",
    generalNotes: "Need Soncap certification and Form M export documentation.",
    status: "NEED_INFORMATION",
    items: [
      {
        id: "rfq_item_110_1",
        productId: "prd0005",
        productName: "Slim Fit Chino Trousers",
        productSlug: "slim-fit-chino-trousers",
        brand: "Zara",
        sku: "ZARA-CHN-005",
        image: "https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        selectedColor: "Khaki / Navy",
        selectedSize: "30-38",
        quantity: 400,
        moq: 50,
        unitPrice: 18.00,
        targetPrice: 16.00,
      },
    ],
    messages: [
      {
        id: "msg_110_1",
        rfqId: "rfq_demo_110",
        senderRole: "admin",
        senderName: "Ayaan Compliance Desk",
        message: "Hello Amara, please provide your authorized Form M agent number in Lagos so we can quote custom clearing.",
        createdAt: "2026-09-19T11:00:00.000Z",
      },
    ],
    history: [
      {
        id: "hist_110_1",
        rfqId: "rfq_demo_110",
        status: "SUBMITTED",
        actorName: "Amara Okafor",
        createdAt: "2026-08-27T10:00:00Z",
      },
      {
        id: "hist_110_2",
        rfqId: "rfq_demo_110",
        status: "NEED_INFORMATION",
        actorName: "Admin",
        note: "Requested Form M regulatory clarification",
        createdAt: "2026-08-28T14:00:00Z",
      },
    ],
    createdAt: "2026-08-27T10:00:00Z",
    updatedAt: "2026-09-19T11:30:00.000Z",
  },
  {
    id: "rfq_demo_111",
    rfqNumber: "RFQ-2026-000111",
    userId: "usr_111",
    buyerName: "Carlos Mendez",
    buyerEmail: "c.mendez@iberianfashion.es",
    buyerPhone: "+34 91 123 4567",
    companyName: "Iberian Fashion S.L.",
    businessType: "Wholesaler",
    destinationCountry: "Spain",
    destinationCity: "Madrid",
    shippingPort: "Port of Valencia / Barajas Airport",
    targetDeliveryDate: "2026-11-20",
    requestTitle: "Classic Denim Jackets for Spanish Outlet Network",
    generalNotes: "Spanish and Portuguese wash care tags required.",
    status: "SUBMITTED",
    items: [
      {
        id: "rfq_item_111_1",
        productId: "prd0002",
        productName: "Classic Denim Jacket",
        productSlug: "classic-denim-jacket",
        brand: "Ayaan",
        sku: "AYN-JNS-002",
        image: "https://images.pexels.com/photos/19490409/pexels-photo-19490409.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        quantity: 300,
        moq: 50,
        unitPrice: 32.00,
        targetPrice: 29.00,
      },
    ],
    messages: [],
    history: [
      {
        id: "hist_111_1",
        rfqId: "rfq_demo_111",
        status: "SUBMITTED",
        actorName: "Carlos Mendez",
        createdAt: "2026-09-18T16:40:00.000Z",
      },
    ],
    createdAt: "2026-08-29T10:00:00Z",
    updatedAt: "2026-09-18T17:15:00.000Z",
  },
  {
    id: "rfq_demo_112",
    rfqNumber: "RFQ-2026-000112",
    userId: "usr_112",
    buyerName: "Priya Sharma",
    buyerEmail: "priya@mumbaisilkcotton.in",
    buyerPhone: "+91 22 2345 6789",
    companyName: "Mumbai Silk & Cotton Co",
    businessType: "Apparel Chain",
    destinationCountry: "India",
    destinationCity: "Mumbai",
    shippingPort: "Nhava Sheva Port (JNPT)",
    targetDeliveryDate: "2026-12-05",
    requestTitle: "1000 Pcs Pima Cotton Tees for E-Commerce Catalog",
    generalNotes: "Bulk polybag packing with individual silica gel packets.",
    status: "UNDER_REVIEW",
    items: [
      {
        id: "rfq_item_112_1",
        productId: "prd0001",
        productName: "Essential Cotton T-Shirt",
        productSlug: "essential-cotton-t-shirt",
        brand: "Levi's",
        sku: "LEVIS-TSH-M-BLK-M-PRD0001",
        image: "https://images.pexels.com/photos/7658459/pexels-photo-7658459.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        quantity: 1000,
        moq: 50,
        unitPrice: 9.50,
        targetPrice: 8.20,
      },
    ],
    messages: [],
    history: [
      {
        id: "hist_112_1",
        rfqId: "rfq_demo_112",
        status: "SUBMITTED",
        actorName: "Priya Sharma",
        createdAt: "2026-09-17T09:30:00.000Z",
      },
      {
        id: "hist_112_2",
        rfqId: "rfq_demo_112",
        status: "UNDER_REVIEW",
        actorName: "Export Desk",
        createdAt: "2026-08-29T08:00:00Z",
      },
    ],
    createdAt: "2026-08-28T12:00:00Z",
    updatedAt: "2026-09-17T10:00:00.000Z",
  },
  {
    id: "rfq_demo_113",
    rfqNumber: "RFQ-2026-000113",
    userId: "usr_113",
    buyerName: "Hans Gruber",
    buyerEmail: "hans@berlinurban.de",
    buyerPhone: "+49 30 9876 5432",
    companyName: "Berlin Urban Outfitters GmbH",
    businessType: "Streetwear Chain",
    destinationCountry: "Germany",
    destinationCity: "Berlin",
    shippingPort: "Port of Hamburg / Berlin Airport",
    targetDeliveryDate: "2026-11-15",
    requestTitle: "Denim Jackets European Distribution Order",
    generalNotes: "German customs compliance documents and EORI number pre-verified.",
    status: "ACCEPTED",
    items: [
      {
        id: "rfq_item_113_1",
        productId: "prd0002",
        productName: "Classic Denim Jacket",
        productSlug: "classic-denim-jacket",
        brand: "Ayaan",
        sku: "AYN-JNS-002",
        image: "https://images.pexels.com/photos/19490409/pexels-photo-19490409.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        quantity: 250,
        moq: 50,
        unitPrice: 30.00,
        targetPrice: 28.50,
      },
    ],
    messages: [
      {
        id: "msg_113_1",
        rfqId: "rfq_demo_113",
        senderRole: "buyer",
        senderName: "Hans Gruber",
        message: "Quotation accepted. Advance payment of 30% has been transferred to DBBL account.",
        createdAt: "2026-09-15T14:00:00.000Z",
      },
    ],
    history: [
      {
        id: "hist_113_1",
        rfqId: "rfq_demo_113",
        status: "SUBMITTED",
        actorName: "Hans Gruber",
        createdAt: "2026-08-19T09:00:00Z",
      },
      {
        id: "hist_113_2",
        rfqId: "rfq_demo_113",
        status: "ACCEPTED",
        actorName: "Hans Gruber",
        note: "Accepted quotation QT-2026-000113",
        createdAt: "2026-08-21T16:00:00Z",
      },
    ],
    quotationId: "qt_demo_113",
    createdAt: "2026-08-19T09:00:00Z",
    updatedAt: "2026-09-15T14:45:00.000Z",
  },
  {
    id: "rfq_demo_114",
    rfqNumber: "RFQ-2026-000114",
    userId: "usr_114",
    buyerName: "Lucas Silva",
    buyerEmail: "lucas@saopaulotrend.br",
    buyerPhone: "+55 11 98765 4321",
    companyName: "Sao Paulo Trend Retail",
    businessType: "Distributor",
    destinationCountry: "Brazil",
    destinationCity: "Sao Paulo",
    shippingPort: "Port of Santos",
    targetDeliveryDate: "2026-12-20",
    requestTitle: "Graphic Tees batch for Latin America",
    generalNotes: "Quote CNF Santos Port with Portuguese care label instruction.",
    status: "SUBMITTED",
    items: [
      {
        id: "rfq_item_114_1",
        productId: "prd0006",
        productName: "Oversized Streetwear Graphic Tee",
        productSlug: "oversized-streetwear-graphic-tee",
        brand: "Stüssy",
        sku: "STUSSY-TEE-006",
        image: "https://images.pexels.com/photos/8532616/pexels-photo-8532616.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        quantity: 500,
        moq: 50,
        unitPrice: 14.50,
        targetPrice: 12.00,
      },
    ],
    messages: [],
    history: [
      {
        id: "hist_114_1",
        rfqId: "rfq_demo_114",
        status: "SUBMITTED",
        actorName: "Lucas Silva",
        createdAt: "2026-09-13T10:45:00.000Z",
      },
    ],
    createdAt: "2026-08-29T14:30:00Z",
    updatedAt: "2026-09-13T11:15:00.000Z",
  },
  {
    id: "rfq_demo_115",
    rfqNumber: "RFQ-2026-000115",
    userId: "usr_115",
    buyerName: "Fatima Al-Zahra",
    buyerEmail: "fatima@dohaluxury.qa",
    buyerPhone: "+974 4455 6677",
    companyName: "Doha Luxury Textiles",
    businessType: "Wholesaler",
    destinationCountry: "Qatar",
    destinationCity: "Doha",
    shippingPort: "Hamad Port / Hamad Airport",
    targetDeliveryDate: "2026-11-20",
    requestTitle: "Pima Cotton Polos for Corporate Uniform Program",
    generalNotes: "Embroidered chest crest with gold metallic thread.",
    status: "UNDER_REVIEW",
    items: [
      {
        id: "rfq_item_115_1",
        productId: "prd0003",
        productName: "Premium Pima Cotton Polo",
        productSlug: "premium-pima-cotton-polo",
        brand: "Ralph Lauren",
        sku: "RL-POLO-003",
        image: "https://images.pexels.com/photos/1232459/pexels-photo-1232459.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        quantity: 350,
        moq: 50,
        unitPrice: 17.50,
        targetPrice: 15.00,
      },
    ],
    messages: [],
    history: [
      {
        id: "hist_115_1",
        rfqId: "rfq_demo_115",
        status: "SUBMITTED",
        actorName: "Fatima Al-Zahra",
        createdAt: "2026-09-11T17:15:00.000Z",
      },
      {
        id: "hist_115_2",
        rfqId: "rfq_demo_115",
        status: "UNDER_REVIEW",
        actorName: "Admin",
        note: "Reviewing embroidery digitizing fee",
        createdAt: "2026-08-29T09:00:00Z",
      },
    ],
    createdAt: "2026-08-28T16:00:00Z",
    updatedAt: "2026-09-11T17:40:00.000Z",
  },
  {
    id: "rfq_demo_116",
    rfqNumber: "RFQ-2026-000116",
    userId: "usr_116",
    buyerName: "Jack Thompson",
    buyerEmail: "j.thompson@sydneyoutfitters.com.au",
    buyerPhone: "+61 2 9876 5432",
    companyName: "Sydney Outfitters Pty Ltd",
    businessType: "Retail Chain",
    destinationCountry: "Australia",
    destinationCity: "Sydney",
    shippingPort: "Port Botany / Sydney Kingsford",
    targetDeliveryDate: "2026-11-30",
    requestTitle: "Chino trousers wholesale batch for Australian Summer",
    generalNotes: "UPF 50+ sun protection treatment required on cotton twill.",
    status: "QUOTATION_PREPARED",
    items: [
      {
        id: "rfq_item_116_1",
        productId: "prd0005",
        productName: "Slim Fit Chino Trousers",
        productSlug: "slim-fit-chino-trousers",
        brand: "Zara",
        sku: "ZARA-CHN-005",
        image: "https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        quantity: 450,
        moq: 50,
        unitPrice: 19.00,
        targetPrice: 16.50,
      },
    ],
    messages: [
      {
        id: "msg_116_1",
        rfqId: "rfq_demo_116",
        senderRole: "admin",
        senderName: "Ayaan Export Sales",
        message: "Quotation QT-2026-000116 generated with FOB Chittagong pricing and UPF testing report.",
        createdAt: "2026-09-08T13:20:00.000Z",
      },
    ],
    history: [
      {
        id: "hist_116_1",
        rfqId: "rfq_demo_116",
        status: "SUBMITTED",
        actorName: "Jack Thompson",
        createdAt: "2026-08-27T04:00:00Z",
      },
      {
        id: "hist_116_2",
        rfqId: "rfq_demo_116",
        status: "QUOTATION_PREPARED",
        actorName: "Admin",
        createdAt: "2026-08-28T07:30:00Z",
      },
    ],
    quotationId: "qt_demo_116",
    createdAt: "2026-08-27T04:00:00Z",
    updatedAt: "2026-09-08T14:00:00.000Z",
  },
  {
    id: "rfq_demo_117",
    rfqNumber: "RFQ-2026-000117",
    userId: "usr_117",
    buyerName: "Elena Rostova",
    buyerEmail: "elena@balticstyle.pl",
    buyerPhone: "+48 22 123 4567",
    companyName: "Baltic Style Group",
    businessType: "Wholesale Boutique",
    destinationCountry: "Poland",
    destinationCity: "Warsaw",
    shippingPort: "Port of Gdansk",
    targetDeliveryDate: "2026-12-10",
    requestTitle: "Oxford Shirts & Blouses for Central Europe",
    generalNotes: "Please advise sea freight transit time to Port of Gdansk.",
    status: "SUBMITTED",
    items: [
      {
        id: "rfq_item_117_1",
        productId: "prd0008",
        productName: "Oxford Button-Down Shirt",
        productSlug: "oxford-button-down-shirt",
        brand: "Brooks Brothers",
        sku: "BB-OXF-008",
        image: "https://images.pexels.com/photos/297933/pexels-photo-297933.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        quantity: 600,
        moq: 50,
        unitPrice: 19.50,
        targetPrice: 17.00,
      },
    ],
    messages: [],
    history: [
      {
        id: "hist_117_1",
        rfqId: "rfq_demo_117",
        status: "SUBMITTED",
        actorName: "Elena Rostova",
        createdAt: "2026-09-05T11:30:00.000Z",
      },
    ],
    createdAt: "2026-08-29T06:00:00Z",
    updatedAt: "2026-09-05T12:00:00.000Z",
  },
  {
    id: "rfq_demo_118",
    rfqNumber: "RFQ-2026-000118",
    userId: "usr_118",
    buyerName: "Wei Chen",
    buyerEmail: "wei.chen@commercialattire.sg",
    buyerPhone: "+65 6789 0123",
    companyName: "Singapore Commercial Attire",
    businessType: "Corporate Supplier",
    destinationCountry: "Singapore",
    destinationCity: "Singapore",
    shippingPort: "Port of Singapore (PSA)",
    targetDeliveryDate: "2026-11-15",
    requestTitle: "Oxford Formal Shirts Corporate Delivery",
    generalNotes: "Wrinkle-resistant easy care finish required.",
    status: "ACCEPTED",
    items: [
      {
        id: "rfq_item_118_1",
        productId: "prd0008",
        productName: "Oxford Button-Down Shirt",
        productSlug: "oxford-button-down-shirt",
        brand: "Brooks Brothers",
        sku: "BB-OXF-008",
        image: "https://images.pexels.com/photos/297933/pexels-photo-297933.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        quantity: 400,
        moq: 50,
        unitPrice: 18.50,
        targetPrice: 17.50,
      },
    ],
    messages: [],
    history: [
      {
        id: "hist_118_1",
        rfqId: "rfq_demo_118",
        status: "SUBMITTED",
        actorName: "Wei Chen",
        createdAt: "2026-09-03T09:00:00.000Z",
      },
      {
        id: "hist_118_2",
        rfqId: "rfq_demo_118",
        status: "ACCEPTED",
        actorName: "Wei Chen",
        createdAt: "2026-08-23T09:00:00Z",
      },
    ],
    createdAt: "2026-08-20T03:00:00Z",
    updatedAt: "2026-09-03T09:30:00.000Z",
  },
  {
    id: "rfq_demo_119",
    rfqNumber: "RFQ-2026-000119",
    userId: "usr_119",
    buyerName: "Noor Al-Sabah",
    buyerEmail: "noor@kuwaitfashionhouse.kw",
    buyerPhone: "+965 2234 5678",
    companyName: "Kuwait Fashion House",
    businessType: "Wholesale Boutique",
    destinationCountry: "Kuwait",
    destinationCity: "Kuwait City",
    shippingPort: "Shuwaikh Port / Kuwait Airport",
    targetDeliveryDate: "2026-12-01",
    requestTitle: "Waterproof Winter Parkas Luxury Edition",
    generalNotes: "Taped seams with YKK waterproof zippers.",
    status: "SUBMITTED",
    items: [
      {
        id: "rfq_item_119_1",
        productId: "prd0007",
        productName: "Waterproof Winter Parka",
        productSlug: "waterproof-winter-parka",
        brand: "The North Face",
        sku: "TNF-PRK-007",
        image: "https://images.pexels.com/photos/842811/pexels-photo-842811.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        quantity: 250,
        moq: 50,
        unitPrice: 65.00,
        targetPrice: 58.00,
      },
    ],
    messages: [],
    history: [
      {
        id: "hist_119_1",
        rfqId: "rfq_demo_119",
        status: "SUBMITTED",
        actorName: "Noor Al-Sabah",
        createdAt: "2026-09-01T16:10:00.000Z",
      },
    ],
    createdAt: "2026-08-29T13:00:00Z",
    updatedAt: "2026-09-01T16:40:00.000Z",
  },
  {
    id: "rfq_demo_120",
    rfqNumber: "RFQ-2026-000120",
    userId: "usr_120",
    buyerName: "James Wilson",
    buyerEmail: "j.wilson@edinburghtweed.co.uk",
    buyerPhone: "+44 131 496 0789",
    companyName: "Edinburgh Tweed & Knitwear",
    businessType: "Retailer",
    destinationCountry: "United Kingdom",
    destinationCity: "Edinburgh",
    shippingPort: "Port of Grangemouth / Edinburgh Airport",
    targetDeliveryDate: "2026-11-28",
    requestTitle: "Fleece Hoodies with Tartan Hood Lining",
    generalNotes: "Custom inside hood tartan fabric provided by buyer.",
    status: "UNDER_REVIEW",
    items: [
      {
        id: "rfq_item_120_1",
        productId: "prd0004",
        productName: "Heavyweight Fleece Hoodie",
        productSlug: "heavyweight-fleece-hoodie",
        brand: "Champion",
        sku: "CHAMP-HD-004",
        image: "https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        quantity: 500,
        moq: 50,
        unitPrice: 23.00,
        targetPrice: 20.00,
      },
    ],
    messages: [],
    history: [
      {
        id: "hist_120_1",
        rfqId: "rfq_demo_120",
        status: "SUBMITTED",
        actorName: "James Wilson",
        createdAt: "2026-08-30T14:30:00.000Z",
      },
      {
        id: "hist_120_2",
        rfqId: "rfq_demo_120",
        status: "UNDER_REVIEW",
        actorName: "Admin",
        createdAt: "2026-08-28T10:00:00Z",
      },
    ],
    createdAt: "2026-08-27T15:00:00Z",
    updatedAt: "2026-08-30T15:00:00.000Z",
  },
  {
    id: "rfq_demo_121",
    rfqNumber: "RFQ-2026-000121",
    userId: "usr_121",
    buyerName: "Hendrik Van Der Bilt",
    buyerEmail: "hendrik@amsterdamstreetwear.nl",
    buyerPhone: "+31 20 123 4567",
    companyName: "Amsterdam Streetwear BV",
    businessType: "Wholesale Boutique",
    destinationCountry: "Netherlands",
    destinationCity: "Amsterdam",
    shippingPort: "Port of Rotterdam / Schiphol",
    targetDeliveryDate: "2026-10-30",
    requestTitle: "Small trial graphic tee batch (150 pcs)",
    generalNotes: "Need sample run prior to committing to 2,000 units program.",
    status: "REJECTED",
    items: [
      {
        id: "rfq_item_121_1",
        productId: "prd0006",
        productName: "Oversized Streetwear Graphic Tee",
        productSlug: "oversized-streetwear-graphic-tee",
        brand: "Stüssy",
        sku: "STUSSY-TEE-006",
        image: "https://images.pexels.com/photos/8532616/pexels-photo-8532616.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        quantity: 150,
        moq: 50,
        unitPrice: 15.00,
        targetPrice: 11.00,
      },
    ],
    messages: [
      {
        id: "msg_121_1",
        rfqId: "rfq_demo_121",
        senderRole: "admin",
        senderName: "Sales Desk",
        message: "Target price of $11.00 is below production cost for 150 pieces customized wash run.",
        createdAt: "2026-08-28T10:15:00.000Z",
      },
    ],
    history: [
      {
        id: "hist_121_1",
        rfqId: "rfq_demo_121",
        status: "SUBMITTED",
        actorName: "Hendrik Van Der Bilt",
        createdAt: "2026-08-24T09:00:00Z",
      },
      {
        id: "hist_121_2",
        rfqId: "rfq_demo_121",
        status: "REJECTED",
        actorName: "Admin",
        note: "Target price non-viable for requested micro volume",
        createdAt: "2026-08-25T11:00:00Z",
      },
    ],
    createdAt: "2026-08-24T09:00:00Z",
    updatedAt: "2026-08-28T11:00:00.000Z",
  },
  {
    id: "rfq_demo_122",
    rfqNumber: "RFQ-2026-000122",
    userId: "usr_122",
    buyerName: "Kim Min-Jun",
    buyerEmail: "minjun@seoulkstyle.kr",
    buyerPhone: "+82 2 1234 5678",
    companyName: "Seoul K-Style Wholesale",
    businessType: "Wholesaler",
    destinationCountry: "South Korea",
    destinationCity: "Seoul",
    shippingPort: "Busan Port / Incheon Airport",
    targetDeliveryDate: "2026-11-20",
    requestTitle: "Heavyweight Cotton Tees for Dongdaemun Wholesale",
    generalNotes: "Individual frosted ziplock packaging.",
    status: "QUOTATION_PREPARED",
    items: [
      {
        id: "rfq_item_122_1",
        productId: "prd0001",
        productName: "Essential Cotton T-Shirt",
        productSlug: "essential-cotton-t-shirt",
        brand: "Levi's",
        sku: "LEVIS-TSH-M-BLK-M-PRD0001",
        image: "https://images.pexels.com/photos/7658459/pexels-photo-7658459.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        quantity: 750,
        moq: 50,
        unitPrice: 11.00,
        targetPrice: 9.80,
      },
    ],
    messages: [],
    history: [
      {
        id: "hist_122_1",
        rfqId: "rfq_demo_122",
        status: "SUBMITTED",
        actorName: "Kim Min-Jun",
        createdAt: "2026-08-27T15:45:00.000Z",
      },
      {
        id: "hist_122_2",
        rfqId: "rfq_demo_122",
        status: "QUOTATION_PREPARED",
        actorName: "Admin",
        createdAt: "2026-08-27T10:00:00Z",
      },
    ],
    createdAt: "2026-08-26T02:00:00Z",
    updatedAt: "2026-08-27T16:20:00.000Z",
  },
  {
    id: "rfq_demo_123",
    rfqNumber: "RFQ-2026-000123",
    userId: "usr_123",
    buyerName: "Olivia Taylor",
    buyerEmail: "olivia@melbournefashion.com.au",
    buyerPhone: "+61 3 9876 5432",
    companyName: "Melbourne Fashion Collective",
    businessType: "Wholesale Boutique",
    destinationCountry: "Australia",
    destinationCity: "Melbourne",
    shippingPort: "Port of Melbourne",
    targetDeliveryDate: "2026-12-05",
    requestTitle: "Denim Jackets for Autumn Festival Collection",
    generalNotes: "Distressed wash treatment on collar and cuffs.",
    status: "SUBMITTED",
    items: [
      {
        id: "rfq_item_123_1",
        productId: "prd0002",
        productName: "Classic Denim Jacket",
        productSlug: "classic-denim-jacket",
        brand: "Ayaan",
        sku: "AYN-JNS-002",
        image: "https://images.pexels.com/photos/19490409/pexels-photo-19490409.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        quantity: 300,
        moq: 50,
        unitPrice: 31.00,
        targetPrice: 28.00,
      },
    ],
    messages: [],
    history: [
      {
        id: "hist_123_1",
        rfqId: "rfq_demo_123",
        status: "SUBMITTED",
        actorName: "Olivia Taylor",
        createdAt: "2026-08-26T08:30:00.000Z",
      },
    ],
    createdAt: "2026-08-29T03:00:00Z",
    updatedAt: "2026-08-26T09:00:00.000Z",
  },
  {
    id: "rfq_demo_124",
    rfqNumber: "RFQ-2026-000124",
    userId: "usr_124",
    buyerName: "Andreas Schneider",
    buyerEmail: "andreas@zurichtextile.ch",
    buyerPhone: "+41 44 123 4567",
    companyName: "Zurich Textile Trade",
    businessType: "Distributor",
    destinationCountry: "Switzerland",
    destinationCity: "Zurich",
    shippingPort: "Basel Rhine Port / Zurich Airport",
    targetDeliveryDate: "2026-11-30",
    requestTitle: "Pima Polos for Swiss Corporate Gifts",
    generalNotes: "Swiss cross woven mini-label on side seam.",
    status: "UNDER_REVIEW",
    items: [
      {
        id: "rfq_item_124_1",
        productId: "prd0003",
        productName: "Premium Pima Cotton Polo",
        productSlug: "premium-pima-cotton-polo",
        brand: "Ralph Lauren",
        sku: "RL-POLO-003",
        image: "https://images.pexels.com/photos/1232459/pexels-photo-1232459.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        quantity: 400,
        moq: 50,
        unitPrice: 17.00,
        targetPrice: 15.50,
      },
    ],
    messages: [],
    history: [
      {
        id: "hist_124_1",
        rfqId: "rfq_demo_124",
        status: "SUBMITTED",
        actorName: "Andreas Schneider",
        createdAt: "2026-08-25T13:00:00.000Z",
      },
      {
        id: "hist_124_2",
        rfqId: "rfq_demo_124",
        status: "UNDER_REVIEW",
        actorName: "Admin",
        createdAt: "2026-08-28T09:30:00Z",
      },
    ],
    createdAt: "2026-08-27T11:00:00Z",
    updatedAt: "2026-08-25T13:30:00.000Z",
  },
  {
    id: "rfq_demo_125",
    rfqNumber: "RFQ-2026-000125",
    userId: "usr_125",
    buyerName: "Daniel Kim",
    buyerEmail: "d.kim@torontourban.ca",
    buyerPhone: "+1 416 555 0192",
    companyName: "Toronto Urban Goods",
    businessType: "Wholesaler",
    destinationCountry: "Canada",
    destinationCity: "Toronto",
    shippingPort: "Port of Montreal / Toronto Pearson",
    targetDeliveryDate: "2026-11-15",
    requestTitle: "Heavyweight Fleece Hoodies Bulk Order (600 pcs)",
    generalNotes: "Custom Canadian flag tag on sleeve cuff.",
    status: "ACCEPTED",
    items: [
      {
        id: "rfq_item_125_1",
        productId: "prd0004",
        productName: "Heavyweight Fleece Hoodie",
        productSlug: "heavyweight-fleece-hoodie",
        brand: "Champion",
        sku: "CHAMP-HD-004",
        image: "https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        quantity: 600,
        moq: 50,
        unitPrice: 22.50,
        targetPrice: 20.00,
      },
    ],
    messages: [
      {
        id: "msg_125_1",
        rfqId: "rfq_demo_125",
        senderRole: "buyer",
        senderName: "Daniel Kim",
        message: "We have finalized our wholesale contract. Please start lab dip approvals.",
        createdAt: "2026-08-24T11:00:00.000Z",
      },
    ],
    history: [
      {
        id: "hist_125_1",
        rfqId: "rfq_demo_125",
        status: "SUBMITTED",
        actorName: "Daniel Kim",
        createdAt: "2026-08-22T13:00:00Z",
      },
      {
        id: "hist_125_2",
        rfqId: "rfq_demo_125",
        status: "ACCEPTED",
        actorName: "Daniel Kim",
        createdAt: "2026-08-25T17:00:00Z",
      },
    ],
    createdAt: "2026-08-22T13:00:00Z",
    updatedAt: "2026-08-24T11:30:00.000Z",
  },
];
